namespace Otterkit;

public static partial class Tools
{
    // Adapted from: http://www.unicode.org/Public/UNIDATA/CaseFolding.txt
    // License: https://www.unicode.org/license.txt
    
    // The following table is for simple case folding only (mappings with status C + S).
    public static readonly string[] CaseFoldData = new string[]
    {
        "0041", "0061", // LATIN CAPITAL LETTER A
        "0042", "0062", // LATIN CAPITAL LETTER B
        "0043", "0063", // LATIN CAPITAL LETTER C
        "0044", "0064", // LATIN CAPITAL LETTER D
        "0045", "0065", // LATIN CAPITAL LETTER E
        "0046", "0066", // LATIN CAPITAL LETTER F
        "0047", "0067", // LATIN CAPITAL LETTER G
        "0048", "0068", // LATIN CAPITAL LETTER H
        "0049", "0069", // LATIN CAPITAL LETTER I
        "004A", "006A", // LATIN CAPITAL LETTER J
        "004B", "006B", // LATIN CAPITAL LETTER K
        "004C", "006C", // LATIN CAPITAL LETTER L
        "004D", "006D", // LATIN CAPITAL LETTER M
        "004E", "006E", // LATIN CAPITAL LETTER N
        "004F", "006F", // LATIN CAPITAL LETTER O
        "0050", "0070", // LATIN CAPITAL LETTER P
        "0051", "0071", // LATIN CAPITAL LETTER Q
        "0052", "0072", // LATIN CAPITAL LETTER R
        "0053", "0073", // LATIN CAPITAL LETTER S
        "0054", "0074", // LATIN CAPITAL LETTER T
        "0055", "0075", // LATIN CAPITAL LETTER U
        "0056", "0076", // LATIN CAPITAL LETTER V
        "0057", "0077", // LATIN CAPITAL LETTER W
        "0058", "0078", // LATIN CAPITAL LETTER X
        "0059", "0079", // LATIN CAPITAL LETTER Y
        "005A", "007A", // LATIN CAPITAL LETTER Z
        "00B5", "03BC", // MICRO SIGN
        "00C0", "00E0", // LATIN CAPITAL LETTER A WITH GRAVE
        "00C1", "00E1", // LATIN CAPITAL LETTER A WITH ACUTE
        "00C2", "00E2", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
        "00C3", "00E3", // LATIN CAPITAL LETTER A WITH TILDE
        "00C4", "00E4", // LATIN CAPITAL LETTER A WITH DIAERESIS
        "00C5", "00E5", // LATIN CAPITAL LETTER A WITH RING ABOVE
        "00C6", "00E6", // LATIN CAPITAL LETTER AE
        "00C7", "00E7", // LATIN CAPITAL LETTER C WITH CEDILLA
        "00C8", "00E8", // LATIN CAPITAL LETTER E WITH GRAVE
        "00C9", "00E9", // LATIN CAPITAL LETTER E WITH ACUTE
        "00CA", "00EA", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
        "00CB", "00EB", // LATIN CAPITAL LETTER E WITH DIAERESIS
        "00CC", "00EC", // LATIN CAPITAL LETTER I WITH GRAVE
        "00CD", "00ED", // LATIN CAPITAL LETTER I WITH ACUTE
        "00CE", "00EE", // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
        "00CF", "00EF", // LATIN CAPITAL LETTER I WITH DIAERESIS
        "00D0", "00F0", // LATIN CAPITAL LETTER ETH
        "00D1", "00F1", // LATIN CAPITAL LETTER N WITH TILDE
        "00D2", "00F2", // LATIN CAPITAL LETTER O WITH GRAVE
        "00D3", "00F3", // LATIN CAPITAL LETTER O WITH ACUTE
        "00D4", "00F4", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
        "00D5", "00F5", // LATIN CAPITAL LETTER O WITH TILDE
        "00D6", "00F6", // LATIN CAPITAL LETTER O WITH DIAERESIS
        "00D8", "00F8", // LATIN CAPITAL LETTER O WITH STROKE
        "00D9", "00F9", // LATIN CAPITAL LETTER U WITH GRAVE
        "00DA", "00FA", // LATIN CAPITAL LETTER U WITH ACUTE
        "00DB", "00FB", // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
        "00DC", "00FC", // LATIN CAPITAL LETTER U WITH DIAERESIS
        "00DD", "00FD", // LATIN CAPITAL LETTER Y WITH ACUTE
        "00DE", "00FE", // LATIN CAPITAL LETTER THORN
        "0100", "0101", // LATIN CAPITAL LETTER A WITH MACRON
        "0102", "0103", // LATIN CAPITAL LETTER A WITH BREVE
        "0104", "0105", // LATIN CAPITAL LETTER A WITH OGONEK
        "0106", "0107", // LATIN CAPITAL LETTER C WITH ACUTE
        "0108", "0109", // LATIN CAPITAL LETTER C WITH CIRCUMFLEX
        "010A", "010B", // LATIN CAPITAL LETTER C WITH DOT ABOVE
        "010C", "010D", // LATIN CAPITAL LETTER C WITH CARON
        "010E", "010F", // LATIN CAPITAL LETTER D WITH CARON
        "0110", "0111", // LATIN CAPITAL LETTER D WITH STROKE
        "0112", "0113", // LATIN CAPITAL LETTER E WITH MACRON
        "0114", "0115", // LATIN CAPITAL LETTER E WITH BREVE
        "0116", "0117", // LATIN CAPITAL LETTER E WITH DOT ABOVE
        "0118", "0119", // LATIN CAPITAL LETTER E WITH OGONEK
        "011A", "011B", // LATIN CAPITAL LETTER E WITH CARON
        "011C", "011D", // LATIN CAPITAL LETTER G WITH CIRCUMFLEX
        "011E", "011F", // LATIN CAPITAL LETTER G WITH BREVE
        "0120", "0121", // LATIN CAPITAL LETTER G WITH DOT ABOVE
        "0122", "0123", // LATIN CAPITAL LETTER G WITH CEDILLA
        "0124", "0125", // LATIN CAPITAL LETTER H WITH CIRCUMFLEX
        "0126", "0127", // LATIN CAPITAL LETTER H WITH STROKE
        "0128", "0129", // LATIN CAPITAL LETTER I WITH TILDE
        "012A", "012B", // LATIN CAPITAL LETTER I WITH MACRON
        "012C", "012D", // LATIN CAPITAL LETTER I WITH BREVE
        "012E", "012F", // LATIN CAPITAL LETTER I WITH OGONEK
        "0132", "0133", // LATIN CAPITAL LIGATURE IJ
        "0134", "0135", // LATIN CAPITAL LETTER J WITH CIRCUMFLEX
        "0136", "0137", // LATIN CAPITAL LETTER K WITH CEDILLA
        "0139", "013A", // LATIN CAPITAL LETTER L WITH ACUTE
        "013B", "013C", // LATIN CAPITAL LETTER L WITH CEDILLA
        "013D", "013E", // LATIN CAPITAL LETTER L WITH CARON
        "013F", "0140", // LATIN CAPITAL LETTER L WITH MIDDLE DOT
        "0141", "0142", // LATIN CAPITAL LETTER L WITH STROKE
        "0143", "0144", // LATIN CAPITAL LETTER N WITH ACUTE
        "0145", "0146", // LATIN CAPITAL LETTER N WITH CEDILLA
        "0147", "0148", // LATIN CAPITAL LETTER N WITH CARON
        "014A", "014B", // LATIN CAPITAL LETTER ENG
        "014C", "014D", // LATIN CAPITAL LETTER O WITH MACRON
        "014E", "014F", // LATIN CAPITAL LETTER O WITH BREVE
        "0150", "0151", // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
        "0152", "0153", // LATIN CAPITAL LIGATURE OE
        "0154", "0155", // LATIN CAPITAL LETTER R WITH ACUTE
        "0156", "0157", // LATIN CAPITAL LETTER R WITH CEDILLA
        "0158", "0159", // LATIN CAPITAL LETTER R WITH CARON
        "015A", "015B", // LATIN CAPITAL LETTER S WITH ACUTE
        "015C", "015D", // LATIN CAPITAL LETTER S WITH CIRCUMFLEX
        "015E", "015F", // LATIN CAPITAL LETTER S WITH CEDILLA
        "0160", "0161", // LATIN CAPITAL LETTER S WITH CARON
        "0162", "0163", // LATIN CAPITAL LETTER T WITH CEDILLA
        "0164", "0165", // LATIN CAPITAL LETTER T WITH CARON
        "0166", "0167", // LATIN CAPITAL LETTER T WITH STROKE
        "0168", "0169", // LATIN CAPITAL LETTER U WITH TILDE
        "016A", "016B", // LATIN CAPITAL LETTER U WITH MACRON
        "016C", "016D", // LATIN CAPITAL LETTER U WITH BREVE
        "016E", "016F", // LATIN CAPITAL LETTER U WITH RING ABOVE
        "0170", "0171", // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
        "0172", "0173", // LATIN CAPITAL LETTER U WITH OGONEK
        "0174", "0175", // LATIN CAPITAL LETTER W WITH CIRCUMFLEX
        "0176", "0177", // LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
        "0178", "00FF", // LATIN CAPITAL LETTER Y WITH DIAERESIS
        "0179", "017A", // LATIN CAPITAL LETTER Z WITH ACUTE
        "017B", "017C", // LATIN CAPITAL LETTER Z WITH DOT ABOVE
        "017D", "017E", // LATIN CAPITAL LETTER Z WITH CARON
        "017F", "0073", // LATIN SMALL LETTER LONG S
        "0181", "0253", // LATIN CAPITAL LETTER B WITH HOOK
        "0182", "0183", // LATIN CAPITAL LETTER B WITH TOPBAR
        "0184", "0185", // LATIN CAPITAL LETTER TONE SIX
        "0186", "0254", // LATIN CAPITAL LETTER OPEN O
        "0187", "0188", // LATIN CAPITAL LETTER C WITH HOOK
        "0189", "0256", // LATIN CAPITAL LETTER AFRICAN D
        "018A", "0257", // LATIN CAPITAL LETTER D WITH HOOK
        "018B", "018C", // LATIN CAPITAL LETTER D WITH TOPBAR
        "018E", "01DD", // LATIN CAPITAL LETTER REVERSED E
        "018F", "0259", // LATIN CAPITAL LETTER SCHWA
        "0190", "025B", // LATIN CAPITAL LETTER OPEN E
        "0191", "0192", // LATIN CAPITAL LETTER F WITH HOOK
        "0193", "0260", // LATIN CAPITAL LETTER G WITH HOOK
        "0194", "0263", // LATIN CAPITAL LETTER GAMMA
        "0196", "0269", // LATIN CAPITAL LETTER IOTA
        "0197", "0268", // LATIN CAPITAL LETTER I WITH STROKE
        "0198", "0199", // LATIN CAPITAL LETTER K WITH HOOK
        "019C", "026F", // LATIN CAPITAL LETTER TURNED M
        "019D", "0272", // LATIN CAPITAL LETTER N WITH LEFT HOOK
        "019F", "0275", // LATIN CAPITAL LETTER O WITH MIDDLE TILDE
        "01A0", "01A1", // LATIN CAPITAL LETTER O WITH HORN
        "01A2", "01A3", // LATIN CAPITAL LETTER OI
        "01A4", "01A5", // LATIN CAPITAL LETTER P WITH HOOK
        "01A6", "0280", // LATIN LETTER YR
        "01A7", "01A8", // LATIN CAPITAL LETTER TONE TWO
        "01A9", "0283", // LATIN CAPITAL LETTER ESH
        "01AC", "01AD", // LATIN CAPITAL LETTER T WITH HOOK
        "01AE", "0288", // LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
        "01AF", "01B0", // LATIN CAPITAL LETTER U WITH HORN
        "01B1", "028A", // LATIN CAPITAL LETTER UPSILON
        "01B2", "028B", // LATIN CAPITAL LETTER V WITH HOOK
        "01B3", "01B4", // LATIN CAPITAL LETTER Y WITH HOOK
        "01B5", "01B6", // LATIN CAPITAL LETTER Z WITH STROKE
        "01B7", "0292", // LATIN CAPITAL LETTER EZH
        "01B8", "01B9", // LATIN CAPITAL LETTER EZH REVERSED
        "01BC", "01BD", // LATIN CAPITAL LETTER TONE FIVE
        "01C4", "01C6", // LATIN CAPITAL LETTER DZ WITH CARON
        "01C5", "01C6", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
        "01C7", "01C9", // LATIN CAPITAL LETTER LJ
        "01C8", "01C9", // LATIN CAPITAL LETTER L WITH SMALL LETTER J
        "01CA", "01CC", // LATIN CAPITAL LETTER NJ
        "01CB", "01CC", // LATIN CAPITAL LETTER N WITH SMALL LETTER J
        "01CD", "01CE", // LATIN CAPITAL LETTER A WITH CARON
        "01CF", "01D0", // LATIN CAPITAL LETTER I WITH CARON
        "01D1", "01D2", // LATIN CAPITAL LETTER O WITH CARON
        "01D3", "01D4", // LATIN CAPITAL LETTER U WITH CARON
        "01D5", "01D6", // LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
        "01D7", "01D8", // LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
        "01D9", "01DA", // LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
        "01DB", "01DC", // LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
        "01DE", "01DF", // LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
        "01E0", "01E1", // LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
        "01E2", "01E3", // LATIN CAPITAL LETTER AE WITH MACRON
        "01E4", "01E5", // LATIN CAPITAL LETTER G WITH STROKE
        "01E6", "01E7", // LATIN CAPITAL LETTER G WITH CARON
        "01E8", "01E9", // LATIN CAPITAL LETTER K WITH CARON
        "01EA", "01EB", // LATIN CAPITAL LETTER O WITH OGONEK
        "01EC", "01ED", // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
        "01EE", "01EF", // LATIN CAPITAL LETTER EZH WITH CARON
        "01F1", "01F3", // LATIN CAPITAL LETTER DZ
        "01F2", "01F3", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z
        "01F4", "01F5", // LATIN CAPITAL LETTER G WITH ACUTE
        "01F6", "0195", // LATIN CAPITAL LETTER HWAIR
        "01F7", "01BF", // LATIN CAPITAL LETTER WYNN
        "01F8", "01F9", // LATIN CAPITAL LETTER N WITH GRAVE
        "01FA", "01FB", // LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
        "01FC", "01FD", // LATIN CAPITAL LETTER AE WITH ACUTE
        "01FE", "01FF", // LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
        "0200", "0201", // LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
        "0202", "0203", // LATIN CAPITAL LETTER A WITH INVERTED BREVE
        "0204", "0205", // LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
        "0206", "0207", // LATIN CAPITAL LETTER E WITH INVERTED BREVE
        "0208", "0209", // LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
        "020A", "020B", // LATIN CAPITAL LETTER I WITH INVERTED BREVE
        "020C", "020D", // LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
        "020E", "020F", // LATIN CAPITAL LETTER O WITH INVERTED BREVE
        "0210", "0211", // LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
        "0212", "0213", // LATIN CAPITAL LETTER R WITH INVERTED BREVE
        "0214", "0215", // LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
        "0216", "0217", // LATIN CAPITAL LETTER U WITH INVERTED BREVE
        "0218", "0219", // LATIN CAPITAL LETTER S WITH COMMA BELOW
        "021A", "021B", // LATIN CAPITAL LETTER T WITH COMMA BELOW
        "021C", "021D", // LATIN CAPITAL LETTER YOGH
        "021E", "021F", // LATIN CAPITAL LETTER H WITH CARON
        "0220", "019E", // LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
        "0222", "0223", // LATIN CAPITAL LETTER OU
        "0224", "0225", // LATIN CAPITAL LETTER Z WITH HOOK
        "0226", "0227", // LATIN CAPITAL LETTER A WITH DOT ABOVE
        "0228", "0229", // LATIN CAPITAL LETTER E WITH CEDILLA
        "022A", "022B", // LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
        "022C", "022D", // LATIN CAPITAL LETTER O WITH TILDE AND MACRON
        "022E", "022F", // LATIN CAPITAL LETTER O WITH DOT ABOVE
        "0230", "0231", // LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
        "0232", "0233", // LATIN CAPITAL LETTER Y WITH MACRON
        "023A", "2C65", // LATIN CAPITAL LETTER A WITH STROKE
        "023B", "023C", // LATIN CAPITAL LETTER C WITH STROKE
        "023D", "019A", // LATIN CAPITAL LETTER L WITH BAR
        "023E", "2C66", // LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
        "0241", "0242", // LATIN CAPITAL LETTER GLOTTAL STOP
        "0243", "0180", // LATIN CAPITAL LETTER B WITH STROKE
        "0244", "0289", // LATIN CAPITAL LETTER U BAR
        "0245", "028C", // LATIN CAPITAL LETTER TURNED V
        "0246", "0247", // LATIN CAPITAL LETTER E WITH STROKE
        "0248", "0249", // LATIN CAPITAL LETTER J WITH STROKE
        "024A", "024B", // LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL
        "024C", "024D", // LATIN CAPITAL LETTER R WITH STROKE
        "024E", "024F", // LATIN CAPITAL LETTER Y WITH STROKE
        "0345", "03B9", // COMBINING GREEK YPOGEGRAMMENI
        "0370", "0371", // GREEK CAPITAL LETTER HETA
        "0372", "0373", // GREEK CAPITAL LETTER ARCHAIC SAMPI
        "0376", "0377", // GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA
        "037F", "03F3", // GREEK CAPITAL LETTER YOT
        "0386", "03AC", // GREEK CAPITAL LETTER ALPHA WITH TONOS
        "0388", "03AD", // GREEK CAPITAL LETTER EPSILON WITH TONOS
        "0389", "03AE", // GREEK CAPITAL LETTER ETA WITH TONOS
        "038A", "03AF", // GREEK CAPITAL LETTER IOTA WITH TONOS
        "038C", "03CC", // GREEK CAPITAL LETTER OMICRON WITH TONOS
        "038E", "03CD", // GREEK CAPITAL LETTER UPSILON WITH TONOS
        "038F", "03CE", // GREEK CAPITAL LETTER OMEGA WITH TONOS
        "0391", "03B1", // GREEK CAPITAL LETTER ALPHA
        "0392", "03B2", // GREEK CAPITAL LETTER BETA
        "0393", "03B3", // GREEK CAPITAL LETTER GAMMA
        "0394", "03B4", // GREEK CAPITAL LETTER DELTA
        "0395", "03B5", // GREEK CAPITAL LETTER EPSILON
        "0396", "03B6", // GREEK CAPITAL LETTER ZETA
        "0397", "03B7", // GREEK CAPITAL LETTER ETA
        "0398", "03B8", // GREEK CAPITAL LETTER THETA
        "0399", "03B9", // GREEK CAPITAL LETTER IOTA
        "039A", "03BA", // GREEK CAPITAL LETTER KAPPA
        "039B", "03BB", // GREEK CAPITAL LETTER LAMDA
        "039C", "03BC", // GREEK CAPITAL LETTER MU
        "039D", "03BD", // GREEK CAPITAL LETTER NU
        "039E", "03BE", // GREEK CAPITAL LETTER XI
        "039F", "03BF", // GREEK CAPITAL LETTER OMICRON
        "03A0", "03C0", // GREEK CAPITAL LETTER PI
        "03A1", "03C1", // GREEK CAPITAL LETTER RHO
        "03A3", "03C3", // GREEK CAPITAL LETTER SIGMA
        "03A4", "03C4", // GREEK CAPITAL LETTER TAU
        "03A5", "03C5", // GREEK CAPITAL LETTER UPSILON
        "03A6", "03C6", // GREEK CAPITAL LETTER PHI
        "03A7", "03C7", // GREEK CAPITAL LETTER CHI
        "03A8", "03C8", // GREEK CAPITAL LETTER PSI
        "03A9", "03C9", // GREEK CAPITAL LETTER OMEGA
        "03AA", "03CA", // GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
        "03AB", "03CB", // GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
        "03C2", "03C3", // GREEK SMALL LETTER FINAL SIGMA
        "03CF", "03D7", // GREEK CAPITAL KAI SYMBOL
        "03D0", "03B2", // GREEK BETA SYMBOL
        "03D1", "03B8", // GREEK THETA SYMBOL
        "03D5", "03C6", // GREEK PHI SYMBOL
        "03D6", "03C0", // GREEK PI SYMBOL
        "03D8", "03D9", // GREEK LETTER ARCHAIC KOPPA
        "03DA", "03DB", // GREEK LETTER STIGMA
        "03DC", "03DD", // GREEK LETTER DIGAMMA
        "03DE", "03DF", // GREEK LETTER KOPPA
        "03E0", "03E1", // GREEK LETTER SAMPI
        "03E2", "03E3", // COPTIC CAPITAL LETTER SHEI
        "03E4", "03E5", // COPTIC CAPITAL LETTER FEI
        "03E6", "03E7", // COPTIC CAPITAL LETTER KHEI
        "03E8", "03E9", // COPTIC CAPITAL LETTER HORI
        "03EA", "03EB", // COPTIC CAPITAL LETTER GANGIA
        "03EC", "03ED", // COPTIC CAPITAL LETTER SHIMA
        "03EE", "03EF", // COPTIC CAPITAL LETTER DEI
        "03F0", "03BA", // GREEK KAPPA SYMBOL
        "03F1", "03C1", // GREEK RHO SYMBOL
        "03F4", "03B8", // GREEK CAPITAL THETA SYMBOL
        "03F5", "03B5", // GREEK LUNATE EPSILON SYMBOL
        "03F7", "03F8", // GREEK CAPITAL LETTER SHO
        "03F9", "03F2", // GREEK CAPITAL LUNATE SIGMA SYMBOL
        "03FA", "03FB", // GREEK CAPITAL LETTER SAN
        "03FD", "037B", // GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL
        "03FE", "037C", // GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL
        "03FF", "037D", // GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL
        "0400", "0450", // CYRILLIC CAPITAL LETTER IE WITH GRAVE
        "0401", "0451", // CYRILLIC CAPITAL LETTER IO
        "0402", "0452", // CYRILLIC CAPITAL LETTER DJE
        "0403", "0453", // CYRILLIC CAPITAL LETTER GJE
        "0404", "0454", // CYRILLIC CAPITAL LETTER UKRAINIAN IE
        "0405", "0455", // CYRILLIC CAPITAL LETTER DZE
        "0406", "0456", // CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
        "0407", "0457", // CYRILLIC CAPITAL LETTER YI
        "0408", "0458", // CYRILLIC CAPITAL LETTER JE
        "0409", "0459", // CYRILLIC CAPITAL LETTER LJE
        "040A", "045A", // CYRILLIC CAPITAL LETTER NJE
        "040B", "045B", // CYRILLIC CAPITAL LETTER TSHE
        "040C", "045C", // CYRILLIC CAPITAL LETTER KJE
        "040D", "045D", // CYRILLIC CAPITAL LETTER I WITH GRAVE
        "040E", "045E", // CYRILLIC CAPITAL LETTER SHORT U
        "040F", "045F", // CYRILLIC CAPITAL LETTER DZHE
        "0410", "0430", // CYRILLIC CAPITAL LETTER A
        "0411", "0431", // CYRILLIC CAPITAL LETTER BE
        "0412", "0432", // CYRILLIC CAPITAL LETTER VE
        "0413", "0433", // CYRILLIC CAPITAL LETTER GHE
        "0414", "0434", // CYRILLIC CAPITAL LETTER DE
        "0415", "0435", // CYRILLIC CAPITAL LETTER IE
        "0416", "0436", // CYRILLIC CAPITAL LETTER ZHE
        "0417", "0437", // CYRILLIC CAPITAL LETTER ZE
        "0418", "0438", // CYRILLIC CAPITAL LETTER I
        "0419", "0439", // CYRILLIC CAPITAL LETTER SHORT I
        "041A", "043A", // CYRILLIC CAPITAL LETTER KA
        "041B", "043B", // CYRILLIC CAPITAL LETTER EL
        "041C", "043C", // CYRILLIC CAPITAL LETTER EM
        "041D", "043D", // CYRILLIC CAPITAL LETTER EN
        "041E", "043E", // CYRILLIC CAPITAL LETTER O
        "041F", "043F", // CYRILLIC CAPITAL LETTER PE
        "0420", "0440", // CYRILLIC CAPITAL LETTER ER
        "0421", "0441", // CYRILLIC CAPITAL LETTER ES
        "0422", "0442", // CYRILLIC CAPITAL LETTER TE
        "0423", "0443", // CYRILLIC CAPITAL LETTER U
        "0424", "0444", // CYRILLIC CAPITAL LETTER EF
        "0425", "0445", // CYRILLIC CAPITAL LETTER HA
        "0426", "0446", // CYRILLIC CAPITAL LETTER TSE
        "0427", "0447", // CYRILLIC CAPITAL LETTER CHE
        "0428", "0448", // CYRILLIC CAPITAL LETTER SHA
        "0429", "0449", // CYRILLIC CAPITAL LETTER SHCHA
        "042A", "044A", // CYRILLIC CAPITAL LETTER HARD SIGN
        "042B", "044B", // CYRILLIC CAPITAL LETTER YERU
        "042C", "044C", // CYRILLIC CAPITAL LETTER SOFT SIGN
        "042D", "044D", // CYRILLIC CAPITAL LETTER E
        "042E", "044E", // CYRILLIC CAPITAL LETTER YU
        "042F", "044F", // CYRILLIC CAPITAL LETTER YA
        "0460", "0461", // CYRILLIC CAPITAL LETTER OMEGA
        "0462", "0463", // CYRILLIC CAPITAL LETTER YAT
        "0464", "0465", // CYRILLIC CAPITAL LETTER IOTIFIED E
        "0466", "0467", // CYRILLIC CAPITAL LETTER LITTLE YUS
        "0468", "0469", // CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS
        "046A", "046B", // CYRILLIC CAPITAL LETTER BIG YUS
        "046C", "046D", // CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS
        "046E", "046F", // CYRILLIC CAPITAL LETTER KSI
        "0470", "0471", // CYRILLIC CAPITAL LETTER PSI
        "0472", "0473", // CYRILLIC CAPITAL LETTER FITA
        "0474", "0475", // CYRILLIC CAPITAL LETTER IZHITSA
        "0476", "0477", // CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
        "0478", "0479", // CYRILLIC CAPITAL LETTER UK
        "047A", "047B", // CYRILLIC CAPITAL LETTER ROUND OMEGA
        "047C", "047D", // CYRILLIC CAPITAL LETTER OMEGA WITH TITLO
        "047E", "047F", // CYRILLIC CAPITAL LETTER OT
        "0480", "0481", // CYRILLIC CAPITAL LETTER KOPPA
        "048A", "048B", // CYRILLIC CAPITAL LETTER SHORT I WITH TAIL
        "048C", "048D", // CYRILLIC CAPITAL LETTER SEMISOFT SIGN
        "048E", "048F", // CYRILLIC CAPITAL LETTER ER WITH TICK
        "0490", "0491", // CYRILLIC CAPITAL LETTER GHE WITH UPTURN
        "0492", "0493", // CYRILLIC CAPITAL LETTER GHE WITH STROKE
        "0494", "0495", // CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK
        "0496", "0497", // CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER
        "0498", "0499", // CYRILLIC CAPITAL LETTER ZE WITH DESCENDER
        "049A", "049B", // CYRILLIC CAPITAL LETTER KA WITH DESCENDER
        "049C", "049D", // CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE
        "049E", "049F", // CYRILLIC CAPITAL LETTER KA WITH STROKE
        "04A0", "04A1", // CYRILLIC CAPITAL LETTER BASHKIR KA
        "04A2", "04A3", // CYRILLIC CAPITAL LETTER EN WITH DESCENDER
        "04A4", "04A5", // CYRILLIC CAPITAL LIGATURE EN GHE
        "04A6", "04A7", // CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK
        "04A8", "04A9", // CYRILLIC CAPITAL LETTER ABKHASIAN HA
        "04AA", "04AB", // CYRILLIC CAPITAL LETTER ES WITH DESCENDER
        "04AC", "04AD", // CYRILLIC CAPITAL LETTER TE WITH DESCENDER
        "04AE", "04AF", // CYRILLIC CAPITAL LETTER STRAIGHT U
        "04B0", "04B1", // CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE
        "04B2", "04B3", // CYRILLIC CAPITAL LETTER HA WITH DESCENDER
        "04B4", "04B5", // CYRILLIC CAPITAL LIGATURE TE TSE
        "04B6", "04B7", // CYRILLIC CAPITAL LETTER CHE WITH DESCENDER
        "04B8", "04B9", // CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE
        "04BA", "04BB", // CYRILLIC CAPITAL LETTER SHHA
        "04BC", "04BD", // CYRILLIC CAPITAL LETTER ABKHASIAN CHE
        "04BE", "04BF", // CYRILLIC CAPITAL LETTER ABKHASIAN CHE WITH DESCENDER
        "04C0", "04CF", // CYRILLIC LETTER PALOCHKA
        "04C1", "04C2", // CYRILLIC CAPITAL LETTER ZHE WITH BREVE
        "04C3", "04C4", // CYRILLIC CAPITAL LETTER KA WITH HOOK
        "04C5", "04C6", // CYRILLIC CAPITAL LETTER EL WITH TAIL
        "04C7", "04C8", // CYRILLIC CAPITAL LETTER EN WITH HOOK
        "04C9", "04CA", // CYRILLIC CAPITAL LETTER EN WITH TAIL
        "04CB", "04CC", // CYRILLIC CAPITAL LETTER KHAKASSIAN CHE
        "04CD", "04CE", // CYRILLIC CAPITAL LETTER EM WITH TAIL
        "04D0", "04D1", // CYRILLIC CAPITAL LETTER A WITH BREVE
        "04D2", "04D3", // CYRILLIC CAPITAL LETTER A WITH DIAERESIS
        "04D4", "04D5", // CYRILLIC CAPITAL LIGATURE A IE
        "04D6", "04D7", // CYRILLIC CAPITAL LETTER IE WITH BREVE
        "04D8", "04D9", // CYRILLIC CAPITAL LETTER SCHWA
        "04DA", "04DB", // CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
        "04DC", "04DD", // CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
        "04DE", "04DF", // CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
        "04E0", "04E1", // CYRILLIC CAPITAL LETTER ABKHASIAN DZE
        "04E2", "04E3", // CYRILLIC CAPITAL LETTER I WITH MACRON
        "04E4", "04E5", // CYRILLIC CAPITAL LETTER I WITH DIAERESIS
        "04E6", "04E7", // CYRILLIC CAPITAL LETTER O WITH DIAERESIS
        "04E8", "04E9", // CYRILLIC CAPITAL LETTER BARRED O
        "04EA", "04EB", // CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS
        "04EC", "04ED", // CYRILLIC CAPITAL LETTER E WITH DIAERESIS
        "04EE", "04EF", // CYRILLIC CAPITAL LETTER U WITH MACRON
        "04F0", "04F1", // CYRILLIC CAPITAL LETTER U WITH DIAERESIS
        "04F2", "04F3", // CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE
        "04F4", "04F5", // CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
        "04F6", "04F7", // CYRILLIC CAPITAL LETTER GHE WITH DESCENDER
        "04F8", "04F9", // CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS
        "04FA", "04FB", // CYRILLIC CAPITAL LETTER GHE WITH STROKE AND HOOK
        "04FC", "04FD", // CYRILLIC CAPITAL LETTER HA WITH HOOK
        "04FE", "04FF", // CYRILLIC CAPITAL LETTER HA WITH STROKE
        "0500", "0501", // CYRILLIC CAPITAL LETTER KOMI DE
        "0502", "0503", // CYRILLIC CAPITAL LETTER KOMI DJE
        "0504", "0505", // CYRILLIC CAPITAL LETTER KOMI ZJE
        "0506", "0507", // CYRILLIC CAPITAL LETTER KOMI DZJE
        "0508", "0509", // CYRILLIC CAPITAL LETTER KOMI LJE
        "050A", "050B", // CYRILLIC CAPITAL LETTER KOMI NJE
        "050C", "050D", // CYRILLIC CAPITAL LETTER KOMI SJE
        "050E", "050F", // CYRILLIC CAPITAL LETTER KOMI TJE
        "0510", "0511", // CYRILLIC CAPITAL LETTER REVERSED ZE
        "0512", "0513", // CYRILLIC CAPITAL LETTER EL WITH HOOK
        "0514", "0515", // CYRILLIC CAPITAL LETTER LHA
        "0516", "0517", // CYRILLIC CAPITAL LETTER RHA
        "0518", "0519", // CYRILLIC CAPITAL LETTER YAE
        "051A", "051B", // CYRILLIC CAPITAL LETTER QA
        "051C", "051D", // CYRILLIC CAPITAL LETTER WE
        "051E", "051F", // CYRILLIC CAPITAL LETTER ALEUT KA
        "0520", "0521", // CYRILLIC CAPITAL LETTER EL WITH MIDDLE HOOK
        "0522", "0523", // CYRILLIC CAPITAL LETTER EN WITH MIDDLE HOOK
        "0524", "0525", // CYRILLIC CAPITAL LETTER PE WITH DESCENDER
        "0526", "0527", // CYRILLIC CAPITAL LETTER SHHA WITH DESCENDER
        "0528", "0529", // CYRILLIC CAPITAL LETTER EN WITH LEFT HOOK
        "052A", "052B", // CYRILLIC CAPITAL LETTER DZZHE
        "052C", "052D", // CYRILLIC CAPITAL LETTER DCHE
        "052E", "052F", // CYRILLIC CAPITAL LETTER EL WITH DESCENDER
        "0531", "0561", // ARMENIAN CAPITAL LETTER AYB
        "0532", "0562", // ARMENIAN CAPITAL LETTER BEN
        "0533", "0563", // ARMENIAN CAPITAL LETTER GIM
        "0534", "0564", // ARMENIAN CAPITAL LETTER DA
        "0535", "0565", // ARMENIAN CAPITAL LETTER ECH
        "0536", "0566", // ARMENIAN CAPITAL LETTER ZA
        "0537", "0567", // ARMENIAN CAPITAL LETTER EH
        "0538", "0568", // ARMENIAN CAPITAL LETTER ET
        "0539", "0569", // ARMENIAN CAPITAL LETTER TO
        "053A", "056A", // ARMENIAN CAPITAL LETTER ZHE
        "053B", "056B", // ARMENIAN CAPITAL LETTER INI
        "053C", "056C", // ARMENIAN CAPITAL LETTER LIWN
        "053D", "056D", // ARMENIAN CAPITAL LETTER XEH
        "053E", "056E", // ARMENIAN CAPITAL LETTER CA
        "053F", "056F", // ARMENIAN CAPITAL LETTER KEN
        "0540", "0570", // ARMENIAN CAPITAL LETTER HO
        "0541", "0571", // ARMENIAN CAPITAL LETTER JA
        "0542", "0572", // ARMENIAN CAPITAL LETTER GHAD
        "0543", "0573", // ARMENIAN CAPITAL LETTER CHEH
        "0544", "0574", // ARMENIAN CAPITAL LETTER MEN
        "0545", "0575", // ARMENIAN CAPITAL LETTER YI
        "0546", "0576", // ARMENIAN CAPITAL LETTER NOW
        "0547", "0577", // ARMENIAN CAPITAL LETTER SHA
        "0548", "0578", // ARMENIAN CAPITAL LETTER VO
        "0549", "0579", // ARMENIAN CAPITAL LETTER CHA
        "054A", "057A", // ARMENIAN CAPITAL LETTER PEH
        "054B", "057B", // ARMENIAN CAPITAL LETTER JHEH
        "054C", "057C", // ARMENIAN CAPITAL LETTER RA
        "054D", "057D", // ARMENIAN CAPITAL LETTER SEH
        "054E", "057E", // ARMENIAN CAPITAL LETTER VEW
        "054F", "057F", // ARMENIAN CAPITAL LETTER TIWN
        "0550", "0580", // ARMENIAN CAPITAL LETTER REH
        "0551", "0581", // ARMENIAN CAPITAL LETTER CO
        "0552", "0582", // ARMENIAN CAPITAL LETTER YIWN
        "0553", "0583", // ARMENIAN CAPITAL LETTER PIWR
        "0554", "0584", // ARMENIAN CAPITAL LETTER KEH
        "0555", "0585", // ARMENIAN CAPITAL LETTER OH
        "0556", "0586", // ARMENIAN CAPITAL LETTER FEH
        "10A0", "2D00", // GEORGIAN CAPITAL LETTER AN
        "10A1", "2D01", // GEORGIAN CAPITAL LETTER BAN
        "10A2", "2D02", // GEORGIAN CAPITAL LETTER GAN
        "10A3", "2D03", // GEORGIAN CAPITAL LETTER DON
        "10A4", "2D04", // GEORGIAN CAPITAL LETTER EN
        "10A5", "2D05", // GEORGIAN CAPITAL LETTER VIN
        "10A6", "2D06", // GEORGIAN CAPITAL LETTER ZEN
        "10A7", "2D07", // GEORGIAN CAPITAL LETTER TAN
        "10A8", "2D08", // GEORGIAN CAPITAL LETTER IN
        "10A9", "2D09", // GEORGIAN CAPITAL LETTER KAN
        "10AA", "2D0A", // GEORGIAN CAPITAL LETTER LAS
        "10AB", "2D0B", // GEORGIAN CAPITAL LETTER MAN
        "10AC", "2D0C", // GEORGIAN CAPITAL LETTER NAR
        "10AD", "2D0D", // GEORGIAN CAPITAL LETTER ON
        "10AE", "2D0E", // GEORGIAN CAPITAL LETTER PAR
        "10AF", "2D0F", // GEORGIAN CAPITAL LETTER ZHAR
        "10B0", "2D10", // GEORGIAN CAPITAL LETTER RAE
        "10B1", "2D11", // GEORGIAN CAPITAL LETTER SAN
        "10B2", "2D12", // GEORGIAN CAPITAL LETTER TAR
        "10B3", "2D13", // GEORGIAN CAPITAL LETTER UN
        "10B4", "2D14", // GEORGIAN CAPITAL LETTER PHAR
        "10B5", "2D15", // GEORGIAN CAPITAL LETTER KHAR
        "10B6", "2D16", // GEORGIAN CAPITAL LETTER GHAN
        "10B7", "2D17", // GEORGIAN CAPITAL LETTER QAR
        "10B8", "2D18", // GEORGIAN CAPITAL LETTER SHIN
        "10B9", "2D19", // GEORGIAN CAPITAL LETTER CHIN
        "10BA", "2D1A", // GEORGIAN CAPITAL LETTER CAN
        "10BB", "2D1B", // GEORGIAN CAPITAL LETTER JIL
        "10BC", "2D1C", // GEORGIAN CAPITAL LETTER CIL
        "10BD", "2D1D", // GEORGIAN CAPITAL LETTER CHAR
        "10BE", "2D1E", // GEORGIAN CAPITAL LETTER XAN
        "10BF", "2D1F", // GEORGIAN CAPITAL LETTER JHAN
        "10C0", "2D20", // GEORGIAN CAPITAL LETTER HAE
        "10C1", "2D21", // GEORGIAN CAPITAL LETTER HE
        "10C2", "2D22", // GEORGIAN CAPITAL LETTER HIE
        "10C3", "2D23", // GEORGIAN CAPITAL LETTER WE
        "10C4", "2D24", // GEORGIAN CAPITAL LETTER HAR
        "10C5", "2D25", // GEORGIAN CAPITAL LETTER HOE
        "10C7", "2D27", // GEORGIAN CAPITAL LETTER YN
        "10CD", "2D2D", // GEORGIAN CAPITAL LETTER AEN
        "13F8", "13F0", // CHEROKEE SMALL LETTER YE
        "13F9", "13F1", // CHEROKEE SMALL LETTER YI
        "13FA", "13F2", // CHEROKEE SMALL LETTER YO
        "13FB", "13F3", // CHEROKEE SMALL LETTER YU
        "13FC", "13F4", // CHEROKEE SMALL LETTER YV
        "13FD", "13F5", // CHEROKEE SMALL LETTER MV
        "1C80", "0432", // CYRILLIC SMALL LETTER ROUNDED VE
        "1C81", "0434", // CYRILLIC SMALL LETTER LONG-LEGGED DE
        "1C82", "043E", // CYRILLIC SMALL LETTER NARROW O
        "1C83", "0441", // CYRILLIC SMALL LETTER WIDE ES
        "1C84", "0442", // CYRILLIC SMALL LETTER TALL TE
        "1C85", "0442", // CYRILLIC SMALL LETTER THREE-LEGGED TE
        "1C86", "044A", // CYRILLIC SMALL LETTER TALL HARD SIGN
        "1C87", "0463", // CYRILLIC SMALL LETTER TALL YAT
        "1C88", "A64B", // CYRILLIC SMALL LETTER UNBLENDED UK
        "1C90", "10D0", // GEORGIAN MTAVRULI CAPITAL LETTER AN
        "1C91", "10D1", // GEORGIAN MTAVRULI CAPITAL LETTER BAN
        "1C92", "10D2", // GEORGIAN MTAVRULI CAPITAL LETTER GAN
        "1C93", "10D3", // GEORGIAN MTAVRULI CAPITAL LETTER DON
        "1C94", "10D4", // GEORGIAN MTAVRULI CAPITAL LETTER EN
        "1C95", "10D5", // GEORGIAN MTAVRULI CAPITAL LETTER VIN
        "1C96", "10D6", // GEORGIAN MTAVRULI CAPITAL LETTER ZEN
        "1C97", "10D7", // GEORGIAN MTAVRULI CAPITAL LETTER TAN
        "1C98", "10D8", // GEORGIAN MTAVRULI CAPITAL LETTER IN
        "1C99", "10D9", // GEORGIAN MTAVRULI CAPITAL LETTER KAN
        "1C9A", "10DA", // GEORGIAN MTAVRULI CAPITAL LETTER LAS
        "1C9B", "10DB", // GEORGIAN MTAVRULI CAPITAL LETTER MAN
        "1C9C", "10DC", // GEORGIAN MTAVRULI CAPITAL LETTER NAR
        "1C9D", "10DD", // GEORGIAN MTAVRULI CAPITAL LETTER ON
        "1C9E", "10DE", // GEORGIAN MTAVRULI CAPITAL LETTER PAR
        "1C9F", "10DF", // GEORGIAN MTAVRULI CAPITAL LETTER ZHAR
        "1CA0", "10E0", // GEORGIAN MTAVRULI CAPITAL LETTER RAE
        "1CA1", "10E1", // GEORGIAN MTAVRULI CAPITAL LETTER SAN
        "1CA2", "10E2", // GEORGIAN MTAVRULI CAPITAL LETTER TAR
        "1CA3", "10E3", // GEORGIAN MTAVRULI CAPITAL LETTER UN
        "1CA4", "10E4", // GEORGIAN MTAVRULI CAPITAL LETTER PHAR
        "1CA5", "10E5", // GEORGIAN MTAVRULI CAPITAL LETTER KHAR
        "1CA6", "10E6", // GEORGIAN MTAVRULI CAPITAL LETTER GHAN
        "1CA7", "10E7", // GEORGIAN MTAVRULI CAPITAL LETTER QAR
        "1CA8", "10E8", // GEORGIAN MTAVRULI CAPITAL LETTER SHIN
        "1CA9", "10E9", // GEORGIAN MTAVRULI CAPITAL LETTER CHIN
        "1CAA", "10EA", // GEORGIAN MTAVRULI CAPITAL LETTER CAN
        "1CAB", "10EB", // GEORGIAN MTAVRULI CAPITAL LETTER JIL
        "1CAC", "10EC", // GEORGIAN MTAVRULI CAPITAL LETTER CIL
        "1CAD", "10ED", // GEORGIAN MTAVRULI CAPITAL LETTER CHAR
        "1CAE", "10EE", // GEORGIAN MTAVRULI CAPITAL LETTER XAN
        "1CAF", "10EF", // GEORGIAN MTAVRULI CAPITAL LETTER JHAN
        "1CB0", "10F0", // GEORGIAN MTAVRULI CAPITAL LETTER HAE
        "1CB1", "10F1", // GEORGIAN MTAVRULI CAPITAL LETTER HE
        "1CB2", "10F2", // GEORGIAN MTAVRULI CAPITAL LETTER HIE
        "1CB3", "10F3", // GEORGIAN MTAVRULI CAPITAL LETTER WE
        "1CB4", "10F4", // GEORGIAN MTAVRULI CAPITAL LETTER HAR
        "1CB5", "10F5", // GEORGIAN MTAVRULI CAPITAL LETTER HOE
        "1CB6", "10F6", // GEORGIAN MTAVRULI CAPITAL LETTER FI
        "1CB7", "10F7", // GEORGIAN MTAVRULI CAPITAL LETTER YN
        "1CB8", "10F8", // GEORGIAN MTAVRULI CAPITAL LETTER ELIFI
        "1CB9", "10F9", // GEORGIAN MTAVRULI CAPITAL LETTER TURNED GAN
        "1CBA", "10FA", // GEORGIAN MTAVRULI CAPITAL LETTER AIN
        "1CBD", "10FD", // GEORGIAN MTAVRULI CAPITAL LETTER AEN
        "1CBE", "10FE", // GEORGIAN MTAVRULI CAPITAL LETTER HARD SIGN
        "1CBF", "10FF", // GEORGIAN MTAVRULI CAPITAL LETTER LABIAL SIGN
        "1E00", "1E01", // LATIN CAPITAL LETTER A WITH RING BELOW
        "1E02", "1E03", // LATIN CAPITAL LETTER B WITH DOT ABOVE
        "1E04", "1E05", // LATIN CAPITAL LETTER B WITH DOT BELOW
        "1E06", "1E07", // LATIN CAPITAL LETTER B WITH LINE BELOW
        "1E08", "1E09", // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
        "1E0A", "1E0B", // LATIN CAPITAL LETTER D WITH DOT ABOVE
        "1E0C", "1E0D", // LATIN CAPITAL LETTER D WITH DOT BELOW
        "1E0E", "1E0F", // LATIN CAPITAL LETTER D WITH LINE BELOW
        "1E10", "1E11", // LATIN CAPITAL LETTER D WITH CEDILLA
        "1E12", "1E13", // LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
        "1E14", "1E15", // LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
        "1E16", "1E17", // LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
        "1E18", "1E19", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
        "1E1A", "1E1B", // LATIN CAPITAL LETTER E WITH TILDE BELOW
        "1E1C", "1E1D", // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
        "1E1E", "1E1F", // LATIN CAPITAL LETTER F WITH DOT ABOVE
        "1E20", "1E21", // LATIN CAPITAL LETTER G WITH MACRON
        "1E22", "1E23", // LATIN CAPITAL LETTER H WITH DOT ABOVE
        "1E24", "1E25", // LATIN CAPITAL LETTER H WITH DOT BELOW
        "1E26", "1E27", // LATIN CAPITAL LETTER H WITH DIAERESIS
        "1E28", "1E29", // LATIN CAPITAL LETTER H WITH CEDILLA
        "1E2A", "1E2B", // LATIN CAPITAL LETTER H WITH BREVE BELOW
        "1E2C", "1E2D", // LATIN CAPITAL LETTER I WITH TILDE BELOW
        "1E2E", "1E2F", // LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
        "1E30", "1E31", // LATIN CAPITAL LETTER K WITH ACUTE
        "1E32", "1E33", // LATIN CAPITAL LETTER K WITH DOT BELOW
        "1E34", "1E35", // LATIN CAPITAL LETTER K WITH LINE BELOW
        "1E36", "1E37", // LATIN CAPITAL LETTER L WITH DOT BELOW
        "1E38", "1E39", // LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
        "1E3A", "1E3B", // LATIN CAPITAL LETTER L WITH LINE BELOW
        "1E3C", "1E3D", // LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
        "1E3E", "1E3F", // LATIN CAPITAL LETTER M WITH ACUTE
        "1E40", "1E41", // LATIN CAPITAL LETTER M WITH DOT ABOVE
        "1E42", "1E43", // LATIN CAPITAL LETTER M WITH DOT BELOW
        "1E44", "1E45", // LATIN CAPITAL LETTER N WITH DOT ABOVE
        "1E46", "1E47", // LATIN CAPITAL LETTER N WITH DOT BELOW
        "1E48", "1E49", // LATIN CAPITAL LETTER N WITH LINE BELOW
        "1E4A", "1E4B", // LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
        "1E4C", "1E4D", // LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
        "1E4E", "1E4F", // LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
        "1E50", "1E51", // LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
        "1E52", "1E53", // LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
        "1E54", "1E55", // LATIN CAPITAL LETTER P WITH ACUTE
        "1E56", "1E57", // LATIN CAPITAL LETTER P WITH DOT ABOVE
        "1E58", "1E59", // LATIN CAPITAL LETTER R WITH DOT ABOVE
        "1E5A", "1E5B", // LATIN CAPITAL LETTER R WITH DOT BELOW
        "1E5C", "1E5D", // LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
        "1E5E", "1E5F", // LATIN CAPITAL LETTER R WITH LINE BELOW
        "1E60", "1E61", // LATIN CAPITAL LETTER S WITH DOT ABOVE
        "1E62", "1E63", // LATIN CAPITAL LETTER S WITH DOT BELOW
        "1E64", "1E65", // LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
        "1E66", "1E67", // LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
        "1E68", "1E69", // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
        "1E6A", "1E6B", // LATIN CAPITAL LETTER T WITH DOT ABOVE
        "1E6C", "1E6D", // LATIN CAPITAL LETTER T WITH DOT BELOW
        "1E6E", "1E6F", // LATIN CAPITAL LETTER T WITH LINE BELOW
        "1E70", "1E71", // LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
        "1E72", "1E73", // LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
        "1E74", "1E75", // LATIN CAPITAL LETTER U WITH TILDE BELOW
        "1E76", "1E77", // LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
        "1E78", "1E79", // LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
        "1E7A", "1E7B", // LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
        "1E7C", "1E7D", // LATIN CAPITAL LETTER V WITH TILDE
        "1E7E", "1E7F", // LATIN CAPITAL LETTER V WITH DOT BELOW
        "1E80", "1E81", // LATIN CAPITAL LETTER W WITH GRAVE
        "1E82", "1E83", // LATIN CAPITAL LETTER W WITH ACUTE
        "1E84", "1E85", // LATIN CAPITAL LETTER W WITH DIAERESIS
        "1E86", "1E87", // LATIN CAPITAL LETTER W WITH DOT ABOVE
        "1E88", "1E89", // LATIN CAPITAL LETTER W WITH DOT BELOW
        "1E8A", "1E8B", // LATIN CAPITAL LETTER X WITH DOT ABOVE
        "1E8C", "1E8D", // LATIN CAPITAL LETTER X WITH DIAERESIS
        "1E8E", "1E8F", // LATIN CAPITAL LETTER Y WITH DOT ABOVE
        "1E90", "1E91", // LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
        "1E92", "1E93", // LATIN CAPITAL LETTER Z WITH DOT BELOW
        "1E94", "1E95", // LATIN CAPITAL LETTER Z WITH LINE BELOW
        "1E9B", "1E61", // LATIN SMALL LETTER LONG S WITH DOT ABOVE
        "1E9E", "00DF", // LATIN CAPITAL LETTER SHARP S
        "1EA0", "1EA1", // LATIN CAPITAL LETTER A WITH DOT BELOW
        "1EA2", "1EA3", // LATIN CAPITAL LETTER A WITH HOOK ABOVE
        "1EA4", "1EA5", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
        "1EA6", "1EA7", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
        "1EA8", "1EA9", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
        "1EAA", "1EAB", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
        "1EAC", "1EAD", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
        "1EAE", "1EAF", // LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
        "1EB0", "1EB1", // LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
        "1EB2", "1EB3", // LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
        "1EB4", "1EB5", // LATIN CAPITAL LETTER A WITH BREVE AND TILDE
        "1EB6", "1EB7", // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
        "1EB8", "1EB9", // LATIN CAPITAL LETTER E WITH DOT BELOW
        "1EBA", "1EBB", // LATIN CAPITAL LETTER E WITH HOOK ABOVE
        "1EBC", "1EBD", // LATIN CAPITAL LETTER E WITH TILDE
        "1EBE", "1EBF", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
        "1EC0", "1EC1", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
        "1EC2", "1EC3", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
        "1EC4", "1EC5", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
        "1EC6", "1EC7", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
        "1EC8", "1EC9", // LATIN CAPITAL LETTER I WITH HOOK ABOVE
        "1ECA", "1ECB", // LATIN CAPITAL LETTER I WITH DOT BELOW
        "1ECC", "1ECD", // LATIN CAPITAL LETTER O WITH DOT BELOW
        "1ECE", "1ECF", // LATIN CAPITAL LETTER O WITH HOOK ABOVE
        "1ED0", "1ED1", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
        "1ED2", "1ED3", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
        "1ED4", "1ED5", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
        "1ED6", "1ED7", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
        "1ED8", "1ED9", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
        "1EDA", "1EDB", // LATIN CAPITAL LETTER O WITH HORN AND ACUTE
        "1EDC", "1EDD", // LATIN CAPITAL LETTER O WITH HORN AND GRAVE
        "1EDE", "1EDF", // LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
        "1EE0", "1EE1", // LATIN CAPITAL LETTER O WITH HORN AND TILDE
        "1EE2", "1EE3", // LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
        "1EE4", "1EE5", // LATIN CAPITAL LETTER U WITH DOT BELOW
        "1EE6", "1EE7", // LATIN CAPITAL LETTER U WITH HOOK ABOVE
        "1EE8", "1EE9", // LATIN CAPITAL LETTER U WITH HORN AND ACUTE
        "1EEA", "1EEB", // LATIN CAPITAL LETTER U WITH HORN AND GRAVE
        "1EEC", "1EED", // LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
        "1EEE", "1EEF", // LATIN CAPITAL LETTER U WITH HORN AND TILDE
        "1EF0", "1EF1", // LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
        "1EF2", "1EF3", // LATIN CAPITAL LETTER Y WITH GRAVE
        "1EF4", "1EF5", // LATIN CAPITAL LETTER Y WITH DOT BELOW
        "1EF6", "1EF7", // LATIN CAPITAL LETTER Y WITH HOOK ABOVE
        "1EF8", "1EF9", // LATIN CAPITAL LETTER Y WITH TILDE
        "1EFA", "1EFB", // LATIN CAPITAL LETTER MIDDLE-WELSH LL
        "1EFC", "1EFD", // LATIN CAPITAL LETTER MIDDLE-WELSH V
        "1EFE", "1EFF", // LATIN CAPITAL LETTER Y WITH LOOP
        "1F08", "1F00", // GREEK CAPITAL LETTER ALPHA WITH PSILI
        "1F09", "1F01", // GREEK CAPITAL LETTER ALPHA WITH DASIA
        "1F0A", "1F02", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
        "1F0B", "1F03", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
        "1F0C", "1F04", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
        "1F0D", "1F05", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
        "1F0E", "1F06", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
        "1F0F", "1F07", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
        "1F18", "1F10", // GREEK CAPITAL LETTER EPSILON WITH PSILI
        "1F19", "1F11", // GREEK CAPITAL LETTER EPSILON WITH DASIA
        "1F1A", "1F12", // GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
        "1F1B", "1F13", // GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
        "1F1C", "1F14", // GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
        "1F1D", "1F15", // GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
        "1F28", "1F20", // GREEK CAPITAL LETTER ETA WITH PSILI
        "1F29", "1F21", // GREEK CAPITAL LETTER ETA WITH DASIA
        "1F2A", "1F22", // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
        "1F2B", "1F23", // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
        "1F2C", "1F24", // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
        "1F2D", "1F25", // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
        "1F2E", "1F26", // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
        "1F2F", "1F27", // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
        "1F38", "1F30", // GREEK CAPITAL LETTER IOTA WITH PSILI
        "1F39", "1F31", // GREEK CAPITAL LETTER IOTA WITH DASIA
        "1F3A", "1F32", // GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
        "1F3B", "1F33", // GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
        "1F3C", "1F34", // GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
        "1F3D", "1F35", // GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
        "1F3E", "1F36", // GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
        "1F3F", "1F37", // GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
        "1F48", "1F40", // GREEK CAPITAL LETTER OMICRON WITH PSILI
        "1F49", "1F41", // GREEK CAPITAL LETTER OMICRON WITH DASIA
        "1F4A", "1F42", // GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
        "1F4B", "1F43", // GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
        "1F4C", "1F44", // GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
        "1F4D", "1F45", // GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
        "1F59", "1F51", // GREEK CAPITAL LETTER UPSILON WITH DASIA
        "1F5B", "1F53", // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
        "1F5D", "1F55", // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
        "1F5F", "1F57", // GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
        "1F68", "1F60", // GREEK CAPITAL LETTER OMEGA WITH PSILI
        "1F69", "1F61", // GREEK CAPITAL LETTER OMEGA WITH DASIA
        "1F6A", "1F62", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
        "1F6B", "1F63", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
        "1F6C", "1F64", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
        "1F6D", "1F65", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
        "1F6E", "1F66", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
        "1F6F", "1F67", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
        "1F88", "1F80", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
        "1F89", "1F81", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
        "1F8A", "1F82", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
        "1F8B", "1F83", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
        "1F8C", "1F84", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
        "1F8D", "1F85", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
        "1F8E", "1F86", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
        "1F8F", "1F87", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
        "1F98", "1F90", // GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
        "1F99", "1F91", // GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
        "1F9A", "1F92", // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
        "1F9B", "1F93", // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
        "1F9C", "1F94", // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
        "1F9D", "1F95", // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
        "1F9E", "1F96", // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
        "1F9F", "1F97", // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
        "1FA8", "1FA0", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
        "1FA9", "1FA1", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
        "1FAA", "1FA2", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
        "1FAB", "1FA3", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
        "1FAC", "1FA4", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
        "1FAD", "1FA5", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
        "1FAE", "1FA6", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
        "1FAF", "1FA7", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
        "1FB8", "1FB0", // GREEK CAPITAL LETTER ALPHA WITH VRACHY
        "1FB9", "1FB1", // GREEK CAPITAL LETTER ALPHA WITH MACRON
        "1FBA", "1F70", // GREEK CAPITAL LETTER ALPHA WITH VARIA
        "1FBB", "1F71", // GREEK CAPITAL LETTER ALPHA WITH OXIA
        "1FBC", "1FB3", // GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
        "1FBE", "03B9", // GREEK PROSGEGRAMMENI
        "1FC8", "1F72", // GREEK CAPITAL LETTER EPSILON WITH VARIA
        "1FC9", "1F73", // GREEK CAPITAL LETTER EPSILON WITH OXIA
        "1FCA", "1F74", // GREEK CAPITAL LETTER ETA WITH VARIA
        "1FCB", "1F75", // GREEK CAPITAL LETTER ETA WITH OXIA
        "1FCC", "1FC3", // GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
        "1FD8", "1FD0", // GREEK CAPITAL LETTER IOTA WITH VRACHY
        "1FD9", "1FD1", // GREEK CAPITAL LETTER IOTA WITH MACRON
        "1FDA", "1F76", // GREEK CAPITAL LETTER IOTA WITH VARIA
        "1FDB", "1F77", // GREEK CAPITAL LETTER IOTA WITH OXIA
        "1FE8", "1FE0", // GREEK CAPITAL LETTER UPSILON WITH VRACHY
        "1FE9", "1FE1", // GREEK CAPITAL LETTER UPSILON WITH MACRON
        "1FEA", "1F7A", // GREEK CAPITAL LETTER UPSILON WITH VARIA
        "1FEB", "1F7B", // GREEK CAPITAL LETTER UPSILON WITH OXIA
        "1FEC", "1FE5", // GREEK CAPITAL LETTER RHO WITH DASIA
        "1FF8", "1F78", // GREEK CAPITAL LETTER OMICRON WITH VARIA
        "1FF9", "1F79", // GREEK CAPITAL LETTER OMICRON WITH OXIA
        "1FFA", "1F7C", // GREEK CAPITAL LETTER OMEGA WITH VARIA
        "1FFB", "1F7D", // GREEK CAPITAL LETTER OMEGA WITH OXIA
        "1FFC", "1FF3", // GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
        "2126", "03C9", // OHM SIGN
        "212A", "006B", // KELVIN SIGN
        "212B", "00E5", // ANGSTROM SIGN
        "2132", "214E", // TURNED CAPITAL F
        "2160", "2170", // ROMAN NUMERAL ONE
        "2161", "2171", // ROMAN NUMERAL TWO
        "2162", "2172", // ROMAN NUMERAL THREE
        "2163", "2173", // ROMAN NUMERAL FOUR
        "2164", "2174", // ROMAN NUMERAL FIVE
        "2165", "2175", // ROMAN NUMERAL SIX
        "2166", "2176", // ROMAN NUMERAL SEVEN
        "2167", "2177", // ROMAN NUMERAL EIGHT
        "2168", "2178", // ROMAN NUMERAL NINE
        "2169", "2179", // ROMAN NUMERAL TEN
        "216A", "217A", // ROMAN NUMERAL ELEVEN
        "216B", "217B", // ROMAN NUMERAL TWELVE
        "216C", "217C", // ROMAN NUMERAL FIFTY
        "216D", "217D", // ROMAN NUMERAL ONE HUNDRED
        "216E", "217E", // ROMAN NUMERAL FIVE HUNDRED
        "216F", "217F", // ROMAN NUMERAL ONE THOUSAND
        "2183", "2184", // ROMAN NUMERAL REVERSED ONE HUNDRED
        "24B6", "24D0", // CIRCLED LATIN CAPITAL LETTER A
        "24B7", "24D1", // CIRCLED LATIN CAPITAL LETTER B
        "24B8", "24D2", // CIRCLED LATIN CAPITAL LETTER C
        "24B9", "24D3", // CIRCLED LATIN CAPITAL LETTER D
        "24BA", "24D4", // CIRCLED LATIN CAPITAL LETTER E
        "24BB", "24D5", // CIRCLED LATIN CAPITAL LETTER F
        "24BC", "24D6", // CIRCLED LATIN CAPITAL LETTER G
        "24BD", "24D7", // CIRCLED LATIN CAPITAL LETTER H
        "24BE", "24D8", // CIRCLED LATIN CAPITAL LETTER I
        "24BF", "24D9", // CIRCLED LATIN CAPITAL LETTER J
        "24C0", "24DA", // CIRCLED LATIN CAPITAL LETTER K
        "24C1", "24DB", // CIRCLED LATIN CAPITAL LETTER L
        "24C2", "24DC", // CIRCLED LATIN CAPITAL LETTER M
        "24C3", "24DD", // CIRCLED LATIN CAPITAL LETTER N
        "24C4", "24DE", // CIRCLED LATIN CAPITAL LETTER O
        "24C5", "24DF", // CIRCLED LATIN CAPITAL LETTER P
        "24C6", "24E0", // CIRCLED LATIN CAPITAL LETTER Q
        "24C7", "24E1", // CIRCLED LATIN CAPITAL LETTER R
        "24C8", "24E2", // CIRCLED LATIN CAPITAL LETTER S
        "24C9", "24E3", // CIRCLED LATIN CAPITAL LETTER T
        "24CA", "24E4", // CIRCLED LATIN CAPITAL LETTER U
        "24CB", "24E5", // CIRCLED LATIN CAPITAL LETTER V
        "24CC", "24E6", // CIRCLED LATIN CAPITAL LETTER W
        "24CD", "24E7", // CIRCLED LATIN CAPITAL LETTER X
        "24CE", "24E8", // CIRCLED LATIN CAPITAL LETTER Y
        "24CF", "24E9", // CIRCLED LATIN CAPITAL LETTER Z
        "2C00", "2C30", // GLAGOLITIC CAPITAL LETTER AZU
        "2C01", "2C31", // GLAGOLITIC CAPITAL LETTER BUKY
        "2C02", "2C32", // GLAGOLITIC CAPITAL LETTER VEDE
        "2C03", "2C33", // GLAGOLITIC CAPITAL LETTER GLAGOLI
        "2C04", "2C34", // GLAGOLITIC CAPITAL LETTER DOBRO
        "2C05", "2C35", // GLAGOLITIC CAPITAL LETTER YESTU
        "2C06", "2C36", // GLAGOLITIC CAPITAL LETTER ZHIVETE
        "2C07", "2C37", // GLAGOLITIC CAPITAL LETTER DZELO
        "2C08", "2C38", // GLAGOLITIC CAPITAL LETTER ZEMLJA
        "2C09", "2C39", // GLAGOLITIC CAPITAL LETTER IZHE
        "2C0A", "2C3A", // GLAGOLITIC CAPITAL LETTER INITIAL IZHE
        "2C0B", "2C3B", // GLAGOLITIC CAPITAL LETTER I
        "2C0C", "2C3C", // GLAGOLITIC CAPITAL LETTER DJERVI
        "2C0D", "2C3D", // GLAGOLITIC CAPITAL LETTER KAKO
        "2C0E", "2C3E", // GLAGOLITIC CAPITAL LETTER LJUDIJE
        "2C0F", "2C3F", // GLAGOLITIC CAPITAL LETTER MYSLITE
        "2C10", "2C40", // GLAGOLITIC CAPITAL LETTER NASHI
        "2C11", "2C41", // GLAGOLITIC CAPITAL LETTER ONU
        "2C12", "2C42", // GLAGOLITIC CAPITAL LETTER POKOJI
        "2C13", "2C43", // GLAGOLITIC CAPITAL LETTER RITSI
        "2C14", "2C44", // GLAGOLITIC CAPITAL LETTER SLOVO
        "2C15", "2C45", // GLAGOLITIC CAPITAL LETTER TVRIDO
        "2C16", "2C46", // GLAGOLITIC CAPITAL LETTER UKU
        "2C17", "2C47", // GLAGOLITIC CAPITAL LETTER FRITU
        "2C18", "2C48", // GLAGOLITIC CAPITAL LETTER HERU
        "2C19", "2C49", // GLAGOLITIC CAPITAL LETTER OTU
        "2C1A", "2C4A", // GLAGOLITIC CAPITAL LETTER PE
        "2C1B", "2C4B", // GLAGOLITIC CAPITAL LETTER SHTA
        "2C1C", "2C4C", // GLAGOLITIC CAPITAL LETTER TSI
        "2C1D", "2C4D", // GLAGOLITIC CAPITAL LETTER CHRIVI
        "2C1E", "2C4E", // GLAGOLITIC CAPITAL LETTER SHA
        "2C1F", "2C4F", // GLAGOLITIC CAPITAL LETTER YERU
        "2C20", "2C50", // GLAGOLITIC CAPITAL LETTER YERI
        "2C21", "2C51", // GLAGOLITIC CAPITAL LETTER YATI
        "2C22", "2C52", // GLAGOLITIC CAPITAL LETTER SPIDERY HA
        "2C23", "2C53", // GLAGOLITIC CAPITAL LETTER YU
        "2C24", "2C54", // GLAGOLITIC CAPITAL LETTER SMALL YUS
        "2C25", "2C55", // GLAGOLITIC CAPITAL LETTER SMALL YUS WITH TAIL
        "2C26", "2C56", // GLAGOLITIC CAPITAL LETTER YO
        "2C27", "2C57", // GLAGOLITIC CAPITAL LETTER IOTATED SMALL YUS
        "2C28", "2C58", // GLAGOLITIC CAPITAL LETTER BIG YUS
        "2C29", "2C59", // GLAGOLITIC CAPITAL LETTER IOTATED BIG YUS
        "2C2A", "2C5A", // GLAGOLITIC CAPITAL LETTER FITA
        "2C2B", "2C5B", // GLAGOLITIC CAPITAL LETTER IZHITSA
        "2C2C", "2C5C", // GLAGOLITIC CAPITAL LETTER SHTAPIC
        "2C2D", "2C5D", // GLAGOLITIC CAPITAL LETTER TROKUTASTI A
        "2C2E", "2C5E", // GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE
        "2C2F", "2C5F", // GLAGOLITIC CAPITAL LETTER CAUDATE CHRIVI
        "2C60", "2C61", // LATIN CAPITAL LETTER L WITH DOUBLE BAR
        "2C62", "026B", // LATIN CAPITAL LETTER L WITH MIDDLE TILDE
        "2C63", "1D7D", // LATIN CAPITAL LETTER P WITH STROKE
        "2C64", "027D", // LATIN CAPITAL LETTER R WITH TAIL
        "2C67", "2C68", // LATIN CAPITAL LETTER H WITH DESCENDER
        "2C69", "2C6A", // LATIN CAPITAL LETTER K WITH DESCENDER
        "2C6B", "2C6C", // LATIN CAPITAL LETTER Z WITH DESCENDER
        "2C6D", "0251", // LATIN CAPITAL LETTER ALPHA
        "2C6E", "0271", // LATIN CAPITAL LETTER M WITH HOOK
        "2C6F", "0250", // LATIN CAPITAL LETTER TURNED A
        "2C70", "0252", // LATIN CAPITAL LETTER TURNED ALPHA
        "2C72", "2C73", // LATIN CAPITAL LETTER W WITH HOOK
        "2C75", "2C76", // LATIN CAPITAL LETTER HALF H
        "2C7E", "023F", // LATIN CAPITAL LETTER S WITH SWASH TAIL
        "2C7F", "0240", // LATIN CAPITAL LETTER Z WITH SWASH TAIL
        "2C80", "2C81", // COPTIC CAPITAL LETTER ALFA
        "2C82", "2C83", // COPTIC CAPITAL LETTER VIDA
        "2C84", "2C85", // COPTIC CAPITAL LETTER GAMMA
        "2C86", "2C87", // COPTIC CAPITAL LETTER DALDA
        "2C88", "2C89", // COPTIC CAPITAL LETTER EIE
        "2C8A", "2C8B", // COPTIC CAPITAL LETTER SOU
        "2C8C", "2C8D", // COPTIC CAPITAL LETTER ZATA
        "2C8E", "2C8F", // COPTIC CAPITAL LETTER HATE
        "2C90", "2C91", // COPTIC CAPITAL LETTER THETHE
        "2C92", "2C93", // COPTIC CAPITAL LETTER IAUDA
        "2C94", "2C95", // COPTIC CAPITAL LETTER KAPA
        "2C96", "2C97", // COPTIC CAPITAL LETTER LAULA
        "2C98", "2C99", // COPTIC CAPITAL LETTER MI
        "2C9A", "2C9B", // COPTIC CAPITAL LETTER NI
        "2C9C", "2C9D", // COPTIC CAPITAL LETTER KSI
        "2C9E", "2C9F", // COPTIC CAPITAL LETTER O
        "2CA0", "2CA1", // COPTIC CAPITAL LETTER PI
        "2CA2", "2CA3", // COPTIC CAPITAL LETTER RO
        "2CA4", "2CA5", // COPTIC CAPITAL LETTER SIMA
        "2CA6", "2CA7", // COPTIC CAPITAL LETTER TAU
        "2CA8", "2CA9", // COPTIC CAPITAL LETTER UA
        "2CAA", "2CAB", // COPTIC CAPITAL LETTER FI
        "2CAC", "2CAD", // COPTIC CAPITAL LETTER KHI
        "2CAE", "2CAF", // COPTIC CAPITAL LETTER PSI
        "2CB0", "2CB1", // COPTIC CAPITAL LETTER OOU
        "2CB2", "2CB3", // COPTIC CAPITAL LETTER DIALECT-P ALEF
        "2CB4", "2CB5", // COPTIC CAPITAL LETTER OLD COPTIC AIN
        "2CB6", "2CB7", // COPTIC CAPITAL LETTER CRYPTOGRAMMIC EIE
        "2CB8", "2CB9", // COPTIC CAPITAL LETTER DIALECT-P KAPA
        "2CBA", "2CBB", // COPTIC CAPITAL LETTER DIALECT-P NI
        "2CBC", "2CBD", // COPTIC CAPITAL LETTER CRYPTOGRAMMIC NI
        "2CBE", "2CBF", // COPTIC CAPITAL LETTER OLD COPTIC OOU
        "2CC0", "2CC1", // COPTIC CAPITAL LETTER SAMPI
        "2CC2", "2CC3", // COPTIC CAPITAL LETTER CROSSED SHEI
        "2CC4", "2CC5", // COPTIC CAPITAL LETTER OLD COPTIC SHEI
        "2CC6", "2CC7", // COPTIC CAPITAL LETTER OLD COPTIC ESH
        "2CC8", "2CC9", // COPTIC CAPITAL LETTER AKHMIMIC KHEI
        "2CCA", "2CCB", // COPTIC CAPITAL LETTER DIALECT-P HORI
        "2CCC", "2CCD", // COPTIC CAPITAL LETTER OLD COPTIC HORI
        "2CCE", "2CCF", // COPTIC CAPITAL LETTER OLD COPTIC HA
        "2CD0", "2CD1", // COPTIC CAPITAL LETTER L-SHAPED HA
        "2CD2", "2CD3", // COPTIC CAPITAL LETTER OLD COPTIC HEI
        "2CD4", "2CD5", // COPTIC CAPITAL LETTER OLD COPTIC HAT
        "2CD6", "2CD7", // COPTIC CAPITAL LETTER OLD COPTIC GANGIA
        "2CD8", "2CD9", // COPTIC CAPITAL LETTER OLD COPTIC DJA
        "2CDA", "2CDB", // COPTIC CAPITAL LETTER OLD COPTIC SHIMA
        "2CDC", "2CDD", // COPTIC CAPITAL LETTER OLD NUBIAN SHIMA
        "2CDE", "2CDF", // COPTIC CAPITAL LETTER OLD NUBIAN NGI
        "2CE0", "2CE1", // COPTIC CAPITAL LETTER OLD NUBIAN NYI
        "2CE2", "2CE3", // COPTIC CAPITAL LETTER OLD NUBIAN WAU
        "2CEB", "2CEC", // COPTIC CAPITAL LETTER CRYPTOGRAMMIC SHEI
        "2CED", "2CEE", // COPTIC CAPITAL LETTER CRYPTOGRAMMIC GANGIA
        "2CF2", "2CF3", // COPTIC CAPITAL LETTER BOHAIRIC KHEI
        "A640", "A641", // CYRILLIC CAPITAL LETTER ZEMLYA
        "A642", "A643", // CYRILLIC CAPITAL LETTER DZELO
        "A644", "A645", // CYRILLIC CAPITAL LETTER REVERSED DZE
        "A646", "A647", // CYRILLIC CAPITAL LETTER IOTA
        "A648", "A649", // CYRILLIC CAPITAL LETTER DJERV
        "A64A", "A64B", // CYRILLIC CAPITAL LETTER MONOGRAPH UK
        "A64C", "A64D", // CYRILLIC CAPITAL LETTER BROAD OMEGA
        "A64E", "A64F", // CYRILLIC CAPITAL LETTER NEUTRAL YER
        "A650", "A651", // CYRILLIC CAPITAL LETTER YERU WITH BACK YER
        "A652", "A653", // CYRILLIC CAPITAL LETTER IOTIFIED YAT
        "A654", "A655", // CYRILLIC CAPITAL LETTER REVERSED YU
        "A656", "A657", // CYRILLIC CAPITAL LETTER IOTIFIED A
        "A658", "A659", // CYRILLIC CAPITAL LETTER CLOSED LITTLE YUS
        "A65A", "A65B", // CYRILLIC CAPITAL LETTER BLENDED YUS
        "A65C", "A65D", // CYRILLIC CAPITAL LETTER IOTIFIED CLOSED LITTLE YUS
        "A65E", "A65F", // CYRILLIC CAPITAL LETTER YN
        "A660", "A661", // CYRILLIC CAPITAL LETTER REVERSED TSE
        "A662", "A663", // CYRILLIC CAPITAL LETTER SOFT DE
        "A664", "A665", // CYRILLIC CAPITAL LETTER SOFT EL
        "A666", "A667", // CYRILLIC CAPITAL LETTER SOFT EM
        "A668", "A669", // CYRILLIC CAPITAL LETTER MONOCULAR O
        "A66A", "A66B", // CYRILLIC CAPITAL LETTER BINOCULAR O
        "A66C", "A66D", // CYRILLIC CAPITAL LETTER DOUBLE MONOCULAR O
        "A680", "A681", // CYRILLIC CAPITAL LETTER DWE
        "A682", "A683", // CYRILLIC CAPITAL LETTER DZWE
        "A684", "A685", // CYRILLIC CAPITAL LETTER ZHWE
        "A686", "A687", // CYRILLIC CAPITAL LETTER CCHE
        "A688", "A689", // CYRILLIC CAPITAL LETTER DZZE
        "A68A", "A68B", // CYRILLIC CAPITAL LETTER TE WITH MIDDLE HOOK
        "A68C", "A68D", // CYRILLIC CAPITAL LETTER TWE
        "A68E", "A68F", // CYRILLIC CAPITAL LETTER TSWE
        "A690", "A691", // CYRILLIC CAPITAL LETTER TSSE
        "A692", "A693", // CYRILLIC CAPITAL LETTER TCHE
        "A694", "A695", // CYRILLIC CAPITAL LETTER HWE
        "A696", "A697", // CYRILLIC CAPITAL LETTER SHWE
        "A698", "A699", // CYRILLIC CAPITAL LETTER DOUBLE O
        "A69A", "A69B", // CYRILLIC CAPITAL LETTER CROSSED O
        "A722", "A723", // LATIN CAPITAL LETTER EGYPTOLOGICAL ALEF
        "A724", "A725", // LATIN CAPITAL LETTER EGYPTOLOGICAL AIN
        "A726", "A727", // LATIN CAPITAL LETTER HENG
        "A728", "A729", // LATIN CAPITAL LETTER TZ
        "A72A", "A72B", // LATIN CAPITAL LETTER TRESILLO
        "A72C", "A72D", // LATIN CAPITAL LETTER CUATRILLO
        "A72E", "A72F", // LATIN CAPITAL LETTER CUATRILLO WITH COMMA
        "A732", "A733", // LATIN CAPITAL LETTER AA
        "A734", "A735", // LATIN CAPITAL LETTER AO
        "A736", "A737", // LATIN CAPITAL LETTER AU
        "A738", "A739", // LATIN CAPITAL LETTER AV
        "A73A", "A73B", // LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR
        "A73C", "A73D", // LATIN CAPITAL LETTER AY
        "A73E", "A73F", // LATIN CAPITAL LETTER REVERSED C WITH DOT
        "A740", "A741", // LATIN CAPITAL LETTER K WITH STROKE
        "A742", "A743", // LATIN CAPITAL LETTER K WITH DIAGONAL STROKE
        "A744", "A745", // LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE
        "A746", "A747", // LATIN CAPITAL LETTER BROKEN L
        "A748", "A749", // LATIN CAPITAL LETTER L WITH HIGH STROKE
        "A74A", "A74B", // LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY
        "A74C", "A74D", // LATIN CAPITAL LETTER O WITH LOOP
        "A74E", "A74F", // LATIN CAPITAL LETTER OO
        "A750", "A751", // LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER
        "A752", "A753", // LATIN CAPITAL LETTER P WITH FLOURISH
        "A754", "A755", // LATIN CAPITAL LETTER P WITH SQUIRREL TAIL
        "A756", "A757", // LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER
        "A758", "A759", // LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE
        "A75A", "A75B", // LATIN CAPITAL LETTER R ROTUNDA
        "A75C", "A75D", // LATIN CAPITAL LETTER RUM ROTUNDA
        "A75E", "A75F", // LATIN CAPITAL LETTER V WITH DIAGONAL STROKE
        "A760", "A761", // LATIN CAPITAL LETTER VY
        "A762", "A763", // LATIN CAPITAL LETTER VISIGOTHIC Z
        "A764", "A765", // LATIN CAPITAL LETTER THORN WITH STROKE
        "A766", "A767", // LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER
        "A768", "A769", // LATIN CAPITAL LETTER VEND
        "A76A", "A76B", // LATIN CAPITAL LETTER ET
        "A76C", "A76D", // LATIN CAPITAL LETTER IS
        "A76E", "A76F", // LATIN CAPITAL LETTER CON
        "A779", "A77A", // LATIN CAPITAL LETTER INSULAR D
        "A77B", "A77C", // LATIN CAPITAL LETTER INSULAR F
        "A77D", "1D79", // LATIN CAPITAL LETTER INSULAR G
        "A77E", "A77F", // LATIN CAPITAL LETTER TURNED INSULAR G
        "A780", "A781", // LATIN CAPITAL LETTER TURNED L
        "A782", "A783", // LATIN CAPITAL LETTER INSULAR R
        "A784", "A785", // LATIN CAPITAL LETTER INSULAR S
        "A786", "A787", // LATIN CAPITAL LETTER INSULAR T
        "A78B", "A78C", // LATIN CAPITAL LETTER SALTILLO
        "A78D", "0265", // LATIN CAPITAL LETTER TURNED H
        "A790", "A791", // LATIN CAPITAL LETTER N WITH DESCENDER
        "A792", "A793", // LATIN CAPITAL LETTER C WITH BAR
        "A796", "A797", // LATIN CAPITAL LETTER B WITH FLOURISH
        "A798", "A799", // LATIN CAPITAL LETTER F WITH STROKE
        "A79A", "A79B", // LATIN CAPITAL LETTER VOLAPUK AE
        "A79C", "A79D", // LATIN CAPITAL LETTER VOLAPUK OE
        "A79E", "A79F", // LATIN CAPITAL LETTER VOLAPUK UE
        "A7A0", "A7A1", // LATIN CAPITAL LETTER G WITH OBLIQUE STROKE
        "A7A2", "A7A3", // LATIN CAPITAL LETTER K WITH OBLIQUE STROKE
        "A7A4", "A7A5", // LATIN CAPITAL LETTER N WITH OBLIQUE STROKE
        "A7A6", "A7A7", // LATIN CAPITAL LETTER R WITH OBLIQUE STROKE
        "A7A8", "A7A9", // LATIN CAPITAL LETTER S WITH OBLIQUE STROKE
        "A7AA", "0266", // LATIN CAPITAL LETTER H WITH HOOK
        "A7AB", "025C", // LATIN CAPITAL LETTER REVERSED OPEN E
        "A7AC", "0261", // LATIN CAPITAL LETTER SCRIPT G
        "A7AD", "026C", // LATIN CAPITAL LETTER L WITH BELT
        "A7AE", "026A", // LATIN CAPITAL LETTER SMALL CAPITAL I
        "A7B0", "029E", // LATIN CAPITAL LETTER TURNED K
        "A7B1", "0287", // LATIN CAPITAL LETTER TURNED T
        "A7B2", "029D", // LATIN CAPITAL LETTER J WITH CROSSED-TAIL
        "A7B3", "AB53", // LATIN CAPITAL LETTER CHI
        "A7B4", "A7B5", // LATIN CAPITAL LETTER BETA
        "A7B6", "A7B7", // LATIN CAPITAL LETTER OMEGA
        "A7B8", "A7B9", // LATIN CAPITAL LETTER U WITH STROKE
        "A7BA", "A7BB", // LATIN CAPITAL LETTER GLOTTAL A
        "A7BC", "A7BD", // LATIN CAPITAL LETTER GLOTTAL I
        "A7BE", "A7BF", // LATIN CAPITAL LETTER GLOTTAL U
        "A7C0", "A7C1", // LATIN CAPITAL LETTER OLD POLISH O
        "A7C2", "A7C3", // LATIN CAPITAL LETTER ANGLICANA W
        "A7C4", "A794", // LATIN CAPITAL LETTER C WITH PALATAL HOOK
        "A7C5", "0282", // LATIN CAPITAL LETTER S WITH HOOK
        "A7C6", "1D8E", // LATIN CAPITAL LETTER Z WITH PALATAL HOOK
        "A7C7", "A7C8", // LATIN CAPITAL LETTER D WITH SHORT STROKE OVERLAY
        "A7C9", "A7CA", // LATIN CAPITAL LETTER S WITH SHORT STROKE OVERLAY
        "A7D0", "A7D1", // LATIN CAPITAL LETTER CLOSED INSULAR G
        "A7D6", "A7D7", // LATIN CAPITAL LETTER MIDDLE SCOTS S
        "A7D8", "A7D9", // LATIN CAPITAL LETTER SIGMOID S
        "A7F5", "A7F6", // LATIN CAPITAL LETTER REVERSED HALF H
        "AB70", "13A0", // CHEROKEE SMALL LETTER A
        "AB71", "13A1", // CHEROKEE SMALL LETTER E
        "AB72", "13A2", // CHEROKEE SMALL LETTER I
        "AB73", "13A3", // CHEROKEE SMALL LETTER O
        "AB74", "13A4", // CHEROKEE SMALL LETTER U
        "AB75", "13A5", // CHEROKEE SMALL LETTER V
        "AB76", "13A6", // CHEROKEE SMALL LETTER GA
        "AB77", "13A7", // CHEROKEE SMALL LETTER KA
        "AB78", "13A8", // CHEROKEE SMALL LETTER GE
        "AB79", "13A9", // CHEROKEE SMALL LETTER GI
        "AB7A", "13AA", // CHEROKEE SMALL LETTER GO
        "AB7B", "13AB", // CHEROKEE SMALL LETTER GU
        "AB7C", "13AC", // CHEROKEE SMALL LETTER GV
        "AB7D", "13AD", // CHEROKEE SMALL LETTER HA
        "AB7E", "13AE", // CHEROKEE SMALL LETTER HE
        "AB7F", "13AF", // CHEROKEE SMALL LETTER HI
        "AB80", "13B0", // CHEROKEE SMALL LETTER HO
        "AB81", "13B1", // CHEROKEE SMALL LETTER HU
        "AB82", "13B2", // CHEROKEE SMALL LETTER HV
        "AB83", "13B3", // CHEROKEE SMALL LETTER LA
        "AB84", "13B4", // CHEROKEE SMALL LETTER LE
        "AB85", "13B5", // CHEROKEE SMALL LETTER LI
        "AB86", "13B6", // CHEROKEE SMALL LETTER LO
        "AB87", "13B7", // CHEROKEE SMALL LETTER LU
        "AB88", "13B8", // CHEROKEE SMALL LETTER LV
        "AB89", "13B9", // CHEROKEE SMALL LETTER MA
        "AB8A", "13BA", // CHEROKEE SMALL LETTER ME
        "AB8B", "13BB", // CHEROKEE SMALL LETTER MI
        "AB8C", "13BC", // CHEROKEE SMALL LETTER MO
        "AB8D", "13BD", // CHEROKEE SMALL LETTER MU
        "AB8E", "13BE", // CHEROKEE SMALL LETTER NA
        "AB8F", "13BF", // CHEROKEE SMALL LETTER HNA
        "AB90", "13C0", // CHEROKEE SMALL LETTER NAH
        "AB91", "13C1", // CHEROKEE SMALL LETTER NE
        "AB92", "13C2", // CHEROKEE SMALL LETTER NI
        "AB93", "13C3", // CHEROKEE SMALL LETTER NO
        "AB94", "13C4", // CHEROKEE SMALL LETTER NU
        "AB95", "13C5", // CHEROKEE SMALL LETTER NV
        "AB96", "13C6", // CHEROKEE SMALL LETTER QUA
        "AB97", "13C7", // CHEROKEE SMALL LETTER QUE
        "AB98", "13C8", // CHEROKEE SMALL LETTER QUI
        "AB99", "13C9", // CHEROKEE SMALL LETTER QUO
        "AB9A", "13CA", // CHEROKEE SMALL LETTER QUU
        "AB9B", "13CB", // CHEROKEE SMALL LETTER QUV
        "AB9C", "13CC", // CHEROKEE SMALL LETTER SA
        "AB9D", "13CD", // CHEROKEE SMALL LETTER S
        "AB9E", "13CE", // CHEROKEE SMALL LETTER SE
        "AB9F", "13CF", // CHEROKEE SMALL LETTER SI
        "ABA0", "13D0", // CHEROKEE SMALL LETTER SO
        "ABA1", "13D1", // CHEROKEE SMALL LETTER SU
        "ABA2", "13D2", // CHEROKEE SMALL LETTER SV
        "ABA3", "13D3", // CHEROKEE SMALL LETTER DA
        "ABA4", "13D4", // CHEROKEE SMALL LETTER TA
        "ABA5", "13D5", // CHEROKEE SMALL LETTER DE
        "ABA6", "13D6", // CHEROKEE SMALL LETTER TE
        "ABA7", "13D7", // CHEROKEE SMALL LETTER DI
        "ABA8", "13D8", // CHEROKEE SMALL LETTER TI
        "ABA9", "13D9", // CHEROKEE SMALL LETTER DO
        "ABAA", "13DA", // CHEROKEE SMALL LETTER DU
        "ABAB", "13DB", // CHEROKEE SMALL LETTER DV
        "ABAC", "13DC", // CHEROKEE SMALL LETTER DLA
        "ABAD", "13DD", // CHEROKEE SMALL LETTER TLA
        "ABAE", "13DE", // CHEROKEE SMALL LETTER TLE
        "ABAF", "13DF", // CHEROKEE SMALL LETTER TLI
        "ABB0", "13E0", // CHEROKEE SMALL LETTER TLO
        "ABB1", "13E1", // CHEROKEE SMALL LETTER TLU
        "ABB2", "13E2", // CHEROKEE SMALL LETTER TLV
        "ABB3", "13E3", // CHEROKEE SMALL LETTER TSA
        "ABB4", "13E4", // CHEROKEE SMALL LETTER TSE
        "ABB5", "13E5", // CHEROKEE SMALL LETTER TSI
        "ABB6", "13E6", // CHEROKEE SMALL LETTER TSO
        "ABB7", "13E7", // CHEROKEE SMALL LETTER TSU
        "ABB8", "13E8", // CHEROKEE SMALL LETTER TSV
        "ABB9", "13E9", // CHEROKEE SMALL LETTER WA
        "ABBA", "13EA", // CHEROKEE SMALL LETTER WE
        "ABBB", "13EB", // CHEROKEE SMALL LETTER WI
        "ABBC", "13EC", // CHEROKEE SMALL LETTER WO
        "ABBD", "13ED", // CHEROKEE SMALL LETTER WU
        "ABBE", "13EE", // CHEROKEE SMALL LETTER WV
        "ABBF", "13EF", // CHEROKEE SMALL LETTER YA
        "FF21", "FF41", // FULLWIDTH LATIN CAPITAL LETTER A
        "FF22", "FF42", // FULLWIDTH LATIN CAPITAL LETTER B
        "FF23", "FF43", // FULLWIDTH LATIN CAPITAL LETTER C
        "FF24", "FF44", // FULLWIDTH LATIN CAPITAL LETTER D
        "FF25", "FF45", // FULLWIDTH LATIN CAPITAL LETTER E
        "FF26", "FF46", // FULLWIDTH LATIN CAPITAL LETTER F
        "FF27", "FF47", // FULLWIDTH LATIN CAPITAL LETTER G
        "FF28", "FF48", // FULLWIDTH LATIN CAPITAL LETTER H
        "FF29", "FF49", // FULLWIDTH LATIN CAPITAL LETTER I
        "FF2A", "FF4A", // FULLWIDTH LATIN CAPITAL LETTER J
        "FF2B", "FF4B", // FULLWIDTH LATIN CAPITAL LETTER K
        "FF2C", "FF4C", // FULLWIDTH LATIN CAPITAL LETTER L
        "FF2D", "FF4D", // FULLWIDTH LATIN CAPITAL LETTER M
        "FF2E", "FF4E", // FULLWIDTH LATIN CAPITAL LETTER N
        "FF2F", "FF4F", // FULLWIDTH LATIN CAPITAL LETTER O
        "FF30", "FF50", // FULLWIDTH LATIN CAPITAL LETTER P
        "FF31", "FF51", // FULLWIDTH LATIN CAPITAL LETTER Q
        "FF32", "FF52", // FULLWIDTH LATIN CAPITAL LETTER R
        "FF33", "FF53", // FULLWIDTH LATIN CAPITAL LETTER S
        "FF34", "FF54", // FULLWIDTH LATIN CAPITAL LETTER T
        "FF35", "FF55", // FULLWIDTH LATIN CAPITAL LETTER U
        "FF36", "FF56", // FULLWIDTH LATIN CAPITAL LETTER V
        "FF37", "FF57", // FULLWIDTH LATIN CAPITAL LETTER W
        "FF38", "FF58", // FULLWIDTH LATIN CAPITAL LETTER X
        "FF39", "FF59", // FULLWIDTH LATIN CAPITAL LETTER Y
        "FF3A", "FF5A", // FULLWIDTH LATIN CAPITAL LETTER Z
        "10400", "10428", // DESERET CAPITAL LETTER LONG I
        "10401", "10429", // DESERET CAPITAL LETTER LONG E
        "10402", "1042A", // DESERET CAPITAL LETTER LONG A
        "10403", "1042B", // DESERET CAPITAL LETTER LONG AH
        "10404", "1042C", // DESERET CAPITAL LETTER LONG O
        "10405", "1042D", // DESERET CAPITAL LETTER LONG OO
        "10406", "1042E", // DESERET CAPITAL LETTER SHORT I
        "10407", "1042F", // DESERET CAPITAL LETTER SHORT E
        "10408", "10430", // DESERET CAPITAL LETTER SHORT A
        "10409", "10431", // DESERET CAPITAL LETTER SHORT AH
        "1040A", "10432", // DESERET CAPITAL LETTER SHORT O
        "1040B", "10433", // DESERET CAPITAL LETTER SHORT OO
        "1040C", "10434", // DESERET CAPITAL LETTER AY
        "1040D", "10435", // DESERET CAPITAL LETTER OW
        "1040E", "10436", // DESERET CAPITAL LETTER WU
        "1040F", "10437", // DESERET CAPITAL LETTER YEE
        "10410", "10438", // DESERET CAPITAL LETTER H
        "10411", "10439", // DESERET CAPITAL LETTER PEE
        "10412", "1043A", // DESERET CAPITAL LETTER BEE
        "10413", "1043B", // DESERET CAPITAL LETTER TEE
        "10414", "1043C", // DESERET CAPITAL LETTER DEE
        "10415", "1043D", // DESERET CAPITAL LETTER CHEE
        "10416", "1043E", // DESERET CAPITAL LETTER JEE
        "10417", "1043F", // DESERET CAPITAL LETTER KAY
        "10418", "10440", // DESERET CAPITAL LETTER GAY
        "10419", "10441", // DESERET CAPITAL LETTER EF
        "1041A", "10442", // DESERET CAPITAL LETTER VEE
        "1041B", "10443", // DESERET CAPITAL LETTER ETH
        "1041C", "10444", // DESERET CAPITAL LETTER THEE
        "1041D", "10445", // DESERET CAPITAL LETTER ES
        "1041E", "10446", // DESERET CAPITAL LETTER ZEE
        "1041F", "10447", // DESERET CAPITAL LETTER ESH
        "10420", "10448", // DESERET CAPITAL LETTER ZHEE
        "10421", "10449", // DESERET CAPITAL LETTER ER
        "10422", "1044A", // DESERET CAPITAL LETTER EL
        "10423", "1044B", // DESERET CAPITAL LETTER EM
        "10424", "1044C", // DESERET CAPITAL LETTER EN
        "10425", "1044D", // DESERET CAPITAL LETTER ENG
        "10426", "1044E", // DESERET CAPITAL LETTER OI
        "10427", "1044F", // DESERET CAPITAL LETTER EW
        "104B0", "104D8", // OSAGE CAPITAL LETTER A
        "104B1", "104D9", // OSAGE CAPITAL LETTER AI
        "104B2", "104DA", // OSAGE CAPITAL LETTER AIN
        "104B3", "104DB", // OSAGE CAPITAL LETTER AH
        "104B4", "104DC", // OSAGE CAPITAL LETTER BRA
        "104B5", "104DD", // OSAGE CAPITAL LETTER CHA
        "104B6", "104DE", // OSAGE CAPITAL LETTER EHCHA
        "104B7", "104DF", // OSAGE CAPITAL LETTER E
        "104B8", "104E0", // OSAGE CAPITAL LETTER EIN
        "104B9", "104E1", // OSAGE CAPITAL LETTER HA
        "104BA", "104E2", // OSAGE CAPITAL LETTER HYA
        "104BB", "104E3", // OSAGE CAPITAL LETTER I
        "104BC", "104E4", // OSAGE CAPITAL LETTER KA
        "104BD", "104E5", // OSAGE CAPITAL LETTER EHKA
        "104BE", "104E6", // OSAGE CAPITAL LETTER KYA
        "104BF", "104E7", // OSAGE CAPITAL LETTER LA
        "104C0", "104E8", // OSAGE CAPITAL LETTER MA
        "104C1", "104E9", // OSAGE CAPITAL LETTER NA
        "104C2", "104EA", // OSAGE CAPITAL LETTER O
        "104C3", "104EB", // OSAGE CAPITAL LETTER OIN
        "104C4", "104EC", // OSAGE CAPITAL LETTER PA
        "104C5", "104ED", // OSAGE CAPITAL LETTER EHPA
        "104C6", "104EE", // OSAGE CAPITAL LETTER SA
        "104C7", "104EF", // OSAGE CAPITAL LETTER SHA
        "104C8", "104F0", // OSAGE CAPITAL LETTER TA
        "104C9", "104F1", // OSAGE CAPITAL LETTER EHTA
        "104CA", "104F2", // OSAGE CAPITAL LETTER TSA
        "104CB", "104F3", // OSAGE CAPITAL LETTER EHTSA
        "104CC", "104F4", // OSAGE CAPITAL LETTER TSHA
        "104CD", "104F5", // OSAGE CAPITAL LETTER DHA
        "104CE", "104F6", // OSAGE CAPITAL LETTER U
        "104CF", "104F7", // OSAGE CAPITAL LETTER WA
        "104D0", "104F8", // OSAGE CAPITAL LETTER KHA
        "104D1", "104F9", // OSAGE CAPITAL LETTER GHA
        "104D2", "104FA", // OSAGE CAPITAL LETTER ZA
        "104D3", "104FB", // OSAGE CAPITAL LETTER ZHA
        "10570", "10597", // VITHKUQI CAPITAL LETTER A
        "10571", "10598", // VITHKUQI CAPITAL LETTER BBE
        "10572", "10599", // VITHKUQI CAPITAL LETTER BE
        "10573", "1059A", // VITHKUQI CAPITAL LETTER CE
        "10574", "1059B", // VITHKUQI CAPITAL LETTER CHE
        "10575", "1059C", // VITHKUQI CAPITAL LETTER DE
        "10576", "1059D", // VITHKUQI CAPITAL LETTER DHE
        "10577", "1059E", // VITHKUQI CAPITAL LETTER EI
        "10578", "1059F", // VITHKUQI CAPITAL LETTER E
        "10579", "105A0", // VITHKUQI CAPITAL LETTER FE
        "1057A", "105A1", // VITHKUQI CAPITAL LETTER GA
        "1057C", "105A3", // VITHKUQI CAPITAL LETTER HA
        "1057D", "105A4", // VITHKUQI CAPITAL LETTER HHA
        "1057E", "105A5", // VITHKUQI CAPITAL LETTER I
        "1057F", "105A6", // VITHKUQI CAPITAL LETTER IJE
        "10580", "105A7", // VITHKUQI CAPITAL LETTER JE
        "10581", "105A8", // VITHKUQI CAPITAL LETTER KA
        "10582", "105A9", // VITHKUQI CAPITAL LETTER LA
        "10583", "105AA", // VITHKUQI CAPITAL LETTER LLA
        "10584", "105AB", // VITHKUQI CAPITAL LETTER ME
        "10585", "105AC", // VITHKUQI CAPITAL LETTER NE
        "10586", "105AD", // VITHKUQI CAPITAL LETTER NJE
        "10587", "105AE", // VITHKUQI CAPITAL LETTER O
        "10588", "105AF", // VITHKUQI CAPITAL LETTER PE
        "10589", "105B0", // VITHKUQI CAPITAL LETTER QA
        "1058A", "105B1", // VITHKUQI CAPITAL LETTER RE
        "1058C", "105B3", // VITHKUQI CAPITAL LETTER SE
        "1058D", "105B4", // VITHKUQI CAPITAL LETTER SHE
        "1058E", "105B5", // VITHKUQI CAPITAL LETTER TE
        "1058F", "105B6", // VITHKUQI CAPITAL LETTER THE
        "10590", "105B7", // VITHKUQI CAPITAL LETTER U
        "10591", "105B8", // VITHKUQI CAPITAL LETTER VE
        "10592", "105B9", // VITHKUQI CAPITAL LETTER XE
        "10594", "105BB", // VITHKUQI CAPITAL LETTER Y
        "10595", "105BC", // VITHKUQI CAPITAL LETTER ZE
        "10C80", "10CC0", // OLD HUNGARIAN CAPITAL LETTER A
        "10C81", "10CC1", // OLD HUNGARIAN CAPITAL LETTER AA
        "10C82", "10CC2", // OLD HUNGARIAN CAPITAL LETTER EB
        "10C83", "10CC3", // OLD HUNGARIAN CAPITAL LETTER AMB
        "10C84", "10CC4", // OLD HUNGARIAN CAPITAL LETTER EC
        "10C85", "10CC5", // OLD HUNGARIAN CAPITAL LETTER ENC
        "10C86", "10CC6", // OLD HUNGARIAN CAPITAL LETTER ECS
        "10C87", "10CC7", // OLD HUNGARIAN CAPITAL LETTER ED
        "10C88", "10CC8", // OLD HUNGARIAN CAPITAL LETTER AND
        "10C89", "10CC9", // OLD HUNGARIAN CAPITAL LETTER E
        "10C8A", "10CCA", // OLD HUNGARIAN CAPITAL LETTER CLOSE E
        "10C8B", "10CCB", // OLD HUNGARIAN CAPITAL LETTER EE
        "10C8C", "10CCC", // OLD HUNGARIAN CAPITAL LETTER EF
        "10C8D", "10CCD", // OLD HUNGARIAN CAPITAL LETTER EG
        "10C8E", "10CCE", // OLD HUNGARIAN CAPITAL LETTER EGY
        "10C8F", "10CCF", // OLD HUNGARIAN CAPITAL LETTER EH
        "10C90", "10CD0", // OLD HUNGARIAN CAPITAL LETTER I
        "10C91", "10CD1", // OLD HUNGARIAN CAPITAL LETTER II
        "10C92", "10CD2", // OLD HUNGARIAN CAPITAL LETTER EJ
        "10C93", "10CD3", // OLD HUNGARIAN CAPITAL LETTER EK
        "10C94", "10CD4", // OLD HUNGARIAN CAPITAL LETTER AK
        "10C95", "10CD5", // OLD HUNGARIAN CAPITAL LETTER UNK
        "10C96", "10CD6", // OLD HUNGARIAN CAPITAL LETTER EL
        "10C97", "10CD7", // OLD HUNGARIAN CAPITAL LETTER ELY
        "10C98", "10CD8", // OLD HUNGARIAN CAPITAL LETTER EM
        "10C99", "10CD9", // OLD HUNGARIAN CAPITAL LETTER EN
        "10C9A", "10CDA", // OLD HUNGARIAN CAPITAL LETTER ENY
        "10C9B", "10CDB", // OLD HUNGARIAN CAPITAL LETTER O
        "10C9C", "10CDC", // OLD HUNGARIAN CAPITAL LETTER OO
        "10C9D", "10CDD", // OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG OE
        "10C9E", "10CDE", // OLD HUNGARIAN CAPITAL LETTER RUDIMENTA OE
        "10C9F", "10CDF", // OLD HUNGARIAN CAPITAL LETTER OEE
        "10CA0", "10CE0", // OLD HUNGARIAN CAPITAL LETTER EP
        "10CA1", "10CE1", // OLD HUNGARIAN CAPITAL LETTER EMP
        "10CA2", "10CE2", // OLD HUNGARIAN CAPITAL LETTER ER
        "10CA3", "10CE3", // OLD HUNGARIAN CAPITAL LETTER SHORT ER
        "10CA4", "10CE4", // OLD HUNGARIAN CAPITAL LETTER ES
        "10CA5", "10CE5", // OLD HUNGARIAN CAPITAL LETTER ESZ
        "10CA6", "10CE6", // OLD HUNGARIAN CAPITAL LETTER ET
        "10CA7", "10CE7", // OLD HUNGARIAN CAPITAL LETTER ENT
        "10CA8", "10CE8", // OLD HUNGARIAN CAPITAL LETTER ETY
        "10CA9", "10CE9", // OLD HUNGARIAN CAPITAL LETTER ECH
        "10CAA", "10CEA", // OLD HUNGARIAN CAPITAL LETTER U
        "10CAB", "10CEB", // OLD HUNGARIAN CAPITAL LETTER UU
        "10CAC", "10CEC", // OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG UE
        "10CAD", "10CED", // OLD HUNGARIAN CAPITAL LETTER RUDIMENTA UE
        "10CAE", "10CEE", // OLD HUNGARIAN CAPITAL LETTER EV
        "10CAF", "10CEF", // OLD HUNGARIAN CAPITAL LETTER EZ
        "10CB0", "10CF0", // OLD HUNGARIAN CAPITAL LETTER EZS
        "10CB1", "10CF1", // OLD HUNGARIAN CAPITAL LETTER ENT-SHAPED SIGN
        "10CB2", "10CF2", // OLD HUNGARIAN CAPITAL LETTER US
        "118A0", "118C0", // WARANG CITI CAPITAL LETTER NGAA
        "118A1", "118C1", // WARANG CITI CAPITAL LETTER A
        "118A2", "118C2", // WARANG CITI CAPITAL LETTER WI
        "118A3", "118C3", // WARANG CITI CAPITAL LETTER YU
        "118A4", "118C4", // WARANG CITI CAPITAL LETTER YA
        "118A5", "118C5", // WARANG CITI CAPITAL LETTER YO
        "118A6", "118C6", // WARANG CITI CAPITAL LETTER II
        "118A7", "118C7", // WARANG CITI CAPITAL LETTER UU
        "118A8", "118C8", // WARANG CITI CAPITAL LETTER E
        "118A9", "118C9", // WARANG CITI CAPITAL LETTER O
        "118AA", "118CA", // WARANG CITI CAPITAL LETTER ANG
        "118AB", "118CB", // WARANG CITI CAPITAL LETTER GA
        "118AC", "118CC", // WARANG CITI CAPITAL LETTER KO
        "118AD", "118CD", // WARANG CITI CAPITAL LETTER ENY
        "118AE", "118CE", // WARANG CITI CAPITAL LETTER YUJ
        "118AF", "118CF", // WARANG CITI CAPITAL LETTER UC
        "118B0", "118D0", // WARANG CITI CAPITAL LETTER ENN
        "118B1", "118D1", // WARANG CITI CAPITAL LETTER ODD
        "118B2", "118D2", // WARANG CITI CAPITAL LETTER TTE
        "118B3", "118D3", // WARANG CITI CAPITAL LETTER NUNG
        "118B4", "118D4", // WARANG CITI CAPITAL LETTER DA
        "118B5", "118D5", // WARANG CITI CAPITAL LETTER AT
        "118B6", "118D6", // WARANG CITI CAPITAL LETTER AM
        "118B7", "118D7", // WARANG CITI CAPITAL LETTER BU
        "118B8", "118D8", // WARANG CITI CAPITAL LETTER PU
        "118B9", "118D9", // WARANG CITI CAPITAL LETTER HIYO
        "118BA", "118DA", // WARANG CITI CAPITAL LETTER HOLO
        "118BB", "118DB", // WARANG CITI CAPITAL LETTER HORR
        "118BC", "118DC", // WARANG CITI CAPITAL LETTER HAR
        "118BD", "118DD", // WARANG CITI CAPITAL LETTER SSUU
        "118BE", "118DE", // WARANG CITI CAPITAL LETTER SII
        "118BF", "118DF", // WARANG CITI CAPITAL LETTER VIYO
        "16E40", "16E60", // MEDEFAIDRIN CAPITAL LETTER M
        "16E41", "16E61", // MEDEFAIDRIN CAPITAL LETTER S
        "16E42", "16E62", // MEDEFAIDRIN CAPITAL LETTER V
        "16E43", "16E63", // MEDEFAIDRIN CAPITAL LETTER W
        "16E44", "16E64", // MEDEFAIDRIN CAPITAL LETTER ATIU
        "16E45", "16E65", // MEDEFAIDRIN CAPITAL LETTER Z
        "16E46", "16E66", // MEDEFAIDRIN CAPITAL LETTER KP
        "16E47", "16E67", // MEDEFAIDRIN CAPITAL LETTER P
        "16E48", "16E68", // MEDEFAIDRIN CAPITAL LETTER T
        "16E49", "16E69", // MEDEFAIDRIN CAPITAL LETTER G
        "16E4A", "16E6A", // MEDEFAIDRIN CAPITAL LETTER F
        "16E4B", "16E6B", // MEDEFAIDRIN CAPITAL LETTER I
        "16E4C", "16E6C", // MEDEFAIDRIN CAPITAL LETTER K
        "16E4D", "16E6D", // MEDEFAIDRIN CAPITAL LETTER A
        "16E4E", "16E6E", // MEDEFAIDRIN CAPITAL LETTER J
        "16E4F", "16E6F", // MEDEFAIDRIN CAPITAL LETTER E
        "16E50", "16E70", // MEDEFAIDRIN CAPITAL LETTER B
        "16E51", "16E71", // MEDEFAIDRIN CAPITAL LETTER C
        "16E52", "16E72", // MEDEFAIDRIN CAPITAL LETTER U
        "16E53", "16E73", // MEDEFAIDRIN CAPITAL LETTER YU
        "16E54", "16E74", // MEDEFAIDRIN CAPITAL LETTER L
        "16E55", "16E75", // MEDEFAIDRIN CAPITAL LETTER Q
        "16E56", "16E76", // MEDEFAIDRIN CAPITAL LETTER HP
        "16E57", "16E77", // MEDEFAIDRIN CAPITAL LETTER NY
        "16E58", "16E78", // MEDEFAIDRIN CAPITAL LETTER X
        "16E59", "16E79", // MEDEFAIDRIN CAPITAL LETTER D
        "16E5A", "16E7A", // MEDEFAIDRIN CAPITAL LETTER OE
        "16E5B", "16E7B", // MEDEFAIDRIN CAPITAL LETTER N
        "16E5C", "16E7C", // MEDEFAIDRIN CAPITAL LETTER R
        "16E5D", "16E7D", // MEDEFAIDRIN CAPITAL LETTER O
        "16E5E", "16E7E", // MEDEFAIDRIN CAPITAL LETTER AI
        "16E5F", "16E7F", // MEDEFAIDRIN CAPITAL LETTER Y
        "1E900", "1E922", // ADLAM CAPITAL LETTER ALIF
        "1E901", "1E923", // ADLAM CAPITAL LETTER DAALI
        "1E902", "1E924", // ADLAM CAPITAL LETTER LAAM
        "1E903", "1E925", // ADLAM CAPITAL LETTER MIIM
        "1E904", "1E926", // ADLAM CAPITAL LETTER BA
        "1E905", "1E927", // ADLAM CAPITAL LETTER SINNYIIYHE
        "1E906", "1E928", // ADLAM CAPITAL LETTER PE
        "1E907", "1E929", // ADLAM CAPITAL LETTER BHE
        "1E908", "1E92A", // ADLAM CAPITAL LETTER RA
        "1E909", "1E92B", // ADLAM CAPITAL LETTER E
        "1E90A", "1E92C", // ADLAM CAPITAL LETTER FA
        "1E90B", "1E92D", // ADLAM CAPITAL LETTER I
        "1E90C", "1E92E", // ADLAM CAPITAL LETTER O
        "1E90D", "1E92F", // ADLAM CAPITAL LETTER DHA
        "1E90E", "1E930", // ADLAM CAPITAL LETTER YHE
        "1E90F", "1E931", // ADLAM CAPITAL LETTER WAW
        "1E910", "1E932", // ADLAM CAPITAL LETTER NUN
        "1E911", "1E933", // ADLAM CAPITAL LETTER KAF
        "1E912", "1E934", // ADLAM CAPITAL LETTER YA
        "1E913", "1E935", // ADLAM CAPITAL LETTER U
        "1E914", "1E936", // ADLAM CAPITAL LETTER JIIM
        "1E915", "1E937", // ADLAM CAPITAL LETTER CHI
        "1E916", "1E938", // ADLAM CAPITAL LETTER HA
        "1E917", "1E939", // ADLAM CAPITAL LETTER QAAF
        "1E918", "1E93A", // ADLAM CAPITAL LETTER GA
        "1E919", "1E93B", // ADLAM CAPITAL LETTER NYA
        "1E91A", "1E93C", // ADLAM CAPITAL LETTER TU
        "1E91B", "1E93D", // ADLAM CAPITAL LETTER NHA
        "1E91C", "1E93E", // ADLAM CAPITAL LETTER VA
        "1E91D", "1E93F", // ADLAM CAPITAL LETTER KHA
        "1E91E", "1E940", // ADLAM CAPITAL LETTER GBE
        "1E91F", "1E941", // ADLAM CAPITAL LETTER ZAL
        "1E920", "1E942", // ADLAM CAPITAL LETTER KPO
        "1E921", "1E943", // ADLAM CAPITAL LETTER SHA
    };
}